insert into Cities (id, Name) values (1, 'Chambar');
insert into Cities (id, Name) values (2, 'Krasnyye Barrikady');
insert into Cities (id, Name) values (3, 'Mojo');
insert into Cities (id, Name) values (4, 'Vazhiny');
insert into Cities (id, Name) values (5, 'Quatá');
insert into Cities (id, Name) values (6, 'Anilao');
insert into Cities (id, Name) values (7, 'Cidadap');
insert into Cities (id, Name) values (8, 'Segezha');
insert into Cities (id, Name) values (9, 'Vitarte');
insert into Cities (id, Name) values (10, 'Laowobao');
insert into Cities (id, Name) values (11, 'Jamaica');
insert into Cities (id, Name) values (12, 'Fullerton');
insert into Cities (id, Name) values (13, 'Yangiyŭl');
insert into Cities (id, Name) values (14, 'Babat');
insert into Cities (id, Name) values (15, 'Yaosai');
insert into Cities (id, Name) values (16, 'Uitiuhtuan');
insert into Cities (id, Name) values (17, 'Äänekoski');
insert into Cities (id, Name) values (18, 'Yangxi');
insert into Cities (id, Name) values (19, 'Örbyhus');
insert into Cities (id, Name) values (20, 'Niimi');
insert into Cities (id, Name) values (21, 'Satovcha');
insert into Cities (id, Name) values (22, 'Belyye Stolby');
insert into Cities (id, Name) values (23, 'Jubb Ramlah');
insert into Cities (id, Name) values (24, 'Hulín');
insert into Cities (id, Name) values (25, 'Pocora');
insert into Cities (id, Name) values (26, 'Wanareja');
insert into Cities (id, Name) values (27, 'Stadtbredimus');
insert into Cities (id, Name) values (28, 'Cabaret');
insert into Cities (id, Name) values (29, 'Balaogan');
insert into Cities (id, Name) values (30, 'Strömsund');
insert into Cities (id, Name) values (31, 'Pak Phanang');
insert into Cities (id, Name) values (32, 'Awgu');
insert into Cities (id, Name) values (33, 'Providencia');
insert into Cities (id, Name) values (34, 'Pustomyty');
insert into Cities (id, Name) values (35, 'Åmål');
insert into Cities (id, Name) values (36, 'Skärholmen');
insert into Cities (id, Name) values (37, 'Banjar Kertasari');
insert into Cities (id, Name) values (38, 'Lianjiangkou');
insert into Cities (id, Name) values (39, 'Malishka');
insert into Cities (id, Name) values (40, 'Ḩawf');
insert into Cities (id, Name) values (41, 'Nelas');
insert into Cities (id, Name) values (42, 'Lanchyn');
insert into Cities (id, Name) values (43, 'Créteil');
insert into Cities (id, Name) values (44, 'Miguel Aleman');
insert into Cities (id, Name) values (45, 'Orekhovo-Borisovo Severnoye');
insert into Cities (id, Name) values (46, 'Yanshang');
insert into Cities (id, Name) values (47, 'San Francisco');
insert into Cities (id, Name) values (48, 'Vairão');
insert into Cities (id, Name) values (49, 'Pokrov');
insert into Cities (id, Name) values (50, 'Kertosari');
insert into Cities (id, Name) values (51, 'Gaoyu');
insert into Cities (id, Name) values (52, 'Mascouche');
insert into Cities (id, Name) values (53, 'Geoktschai');
insert into Cities (id, Name) values (54, 'Madimba');
insert into Cities (id, Name) values (55, 'Kara Suu');
insert into Cities (id, Name) values (56, 'Almalaguês');
insert into Cities (id, Name) values (57, 'Carvalhais');
insert into Cities (id, Name) values (58, 'Jiangkou');
insert into Cities (id, Name) values (59, 'San Jose');
insert into Cities (id, Name) values (60, 'Niederanven');
insert into Cities (id, Name) values (61, 'Montrouge');
insert into Cities (id, Name) values (62, 'Ronggui');
insert into Cities (id, Name) values (63, 'Huangduobu');
insert into Cities (id, Name) values (64, 'Mendeleyevsk');
insert into Cities (id, Name) values (65, 'Gainesville');
insert into Cities (id, Name) values (66, 'Sansanné-Mango');
insert into Cities (id, Name) values (67, 'Obanazawa');
insert into Cities (id, Name) values (68, 'Zhanghua');
insert into Cities (id, Name) values (69, 'Purwosari');
insert into Cities (id, Name) values (70, 'Ciego de Ávila');
insert into Cities (id, Name) values (71, 'Qulsary');
insert into Cities (id, Name) values (72, 'Krajan Suco');
insert into Cities (id, Name) values (73, 'Damiao');
insert into Cities (id, Name) values (74, 'Jinhaihu');
insert into Cities (id, Name) values (75, 'Ayabaca');
insert into Cities (id, Name) values (76, 'Shanjeev Home');
insert into Cities (id, Name) values (77, 'Ad Dabbah');
insert into Cities (id, Name) values (78, 'Stockholm');
insert into Cities (id, Name) values (79, 'Akhaltsikhe');
insert into Cities (id, Name) values (80, 'Taloqan');
insert into Cities (id, Name) values (81, 'Mülheim an der Ruhr');
insert into Cities (id, Name) values (82, 'Västra Frölunda');
insert into Cities (id, Name) values (83, 'Karang');
insert into Cities (id, Name) values (84, 'Esch-sur-Alzette');
insert into Cities (id, Name) values (85, 'Cholpon-Ata');
insert into Cities (id, Name) values (86, 'Dabao');
insert into Cities (id, Name) values (87, 'Heyan');
insert into Cities (id, Name) values (88, 'Taihu');
insert into Cities (id, Name) values (89, 'Sanxi');
insert into Cities (id, Name) values (90, 'Rakhiv');
insert into Cities (id, Name) values (91, 'Sande Vila Nova');
insert into Cities (id, Name) values (92, 'Tríkala');
insert into Cities (id, Name) values (93, 'Edgeworthstown');
insert into Cities (id, Name) values (94, 'Cartagena');
insert into Cities (id, Name) values (95, 'Salerno');
insert into Cities (id, Name) values (96, 'Muzayri‘');
insert into Cities (id, Name) values (97, 'Velas');
insert into Cities (id, Name) values (98, 'Huertas');
insert into Cities (id, Name) values (99, 'Hornówek');
insert into Cities (id, Name) values (100, 'Sundsvall');
insert into Cities (id, Name) values (101, 'Obando');
insert into Cities (id, Name) values (102, 'Mboursou Léré');
insert into Cities (id, Name) values (103, 'Barisan');
insert into Cities (id, Name) values (104, 'Haikou');
insert into Cities (id, Name) values (105, 'Mitake');
insert into Cities (id, Name) values (106, 'Taekas');
insert into Cities (id, Name) values (107, 'Nixi');
insert into Cities (id, Name) values (108, 'Barrio San Luis');
insert into Cities (id, Name) values (109, 'Melun');
insert into Cities (id, Name) values (110, 'Libice nad Cidlinou');
insert into Cities (id, Name) values (111, 'Lenghu');
insert into Cities (id, Name) values (112, 'Tsumeb');
insert into Cities (id, Name) values (113, 'Fanyang');
insert into Cities (id, Name) values (114, 'Bilajari');
insert into Cities (id, Name) values (115, 'Maromme');
insert into Cities (id, Name) values (116, 'Marovoay');
insert into Cities (id, Name) values (117, 'Varser');
insert into Cities (id, Name) values (118, 'Tiebukenwusan');
insert into Cities (id, Name) values (119, 'Chambas');
insert into Cities (id, Name) values (120, 'Harrisburg');
insert into Cities (id, Name) values (121, 'Yasnyy');
insert into Cities (id, Name) values (122, 'Orurillo');
insert into Cities (id, Name) values (123, 'Mpumalanga');
insert into Cities (id, Name) values (124, 'Saparbay');
insert into Cities (id, Name) values (125, 'Venustiano Carranza');
insert into Cities (id, Name) values (126, 'Nekla');
insert into Cities (id, Name) values (127, 'Gangmei');
insert into Cities (id, Name) values (128, 'Wieniawa');
insert into Cities (id, Name) values (129, 'Pantang');
insert into Cities (id, Name) values (130, 'Chenguang');
insert into Cities (id, Name) values (131, 'Jiangguanchi');
insert into Cities (id, Name) values (132, 'Castellon De La Plana/Castello De La Pla');
insert into Cities (id, Name) values (133, 'Nangang');
insert into Cities (id, Name) values (134, 'Akaki');
insert into Cities (id, Name) values (135, 'Mesyagutovo');
insert into Cities (id, Name) values (136, 'Maltahöhe');
insert into Cities (id, Name) values (137, 'Rodez');
insert into Cities (id, Name) values (138, 'Villiers');
insert into Cities (id, Name) values (139, 'Santa Ignacia');
insert into Cities (id, Name) values (140, 'Mudanjiang');
insert into Cities (id, Name) values (141, 'Hadano');
insert into Cities (id, Name) values (142, 'Macapá');
insert into Cities (id, Name) values (143, 'Émpa');
insert into Cities (id, Name) values (144, 'Lingcheng');
insert into Cities (id, Name) values (145, 'Kíti');
insert into Cities (id, Name) values (146, 'Dualing');
insert into Cities (id, Name) values (147, 'Koreiz');
insert into Cities (id, Name) values (148, 'Villa Santa Rita');
insert into Cities (id, Name) values (149, 'Bulls');
insert into Cities (id, Name) values (150, 'Querocotillo');
insert into Cities (id, Name) values (151, 'Senada');
insert into Cities (id, Name) values (152, 'Petani');
insert into Cities (id, Name) values (153, 'Čelinac');
insert into Cities (id, Name) values (154, 'Al Wāsiţah');
insert into Cities (id, Name) values (155, 'Tallahassee');
insert into Cities (id, Name) values (156, 'Youkounkoun');
insert into Cities (id, Name) values (157, 'Longquan');
insert into Cities (id, Name) values (158, 'Vân Tùng');
insert into Cities (id, Name) values (159, 'Rinbung');
insert into Cities (id, Name) values (160, 'Pinheiral');
insert into Cities (id, Name) values (161, 'Aeka');
insert into Cities (id, Name) values (162, 'Svatava');
insert into Cities (id, Name) values (163, 'Cové');
insert into Cities (id, Name) values (164, 'Bejsce');
insert into Cities (id, Name) values (165, 'Oranmore');
insert into Cities (id, Name) values (166, 'Gaofeng');
insert into Cities (id, Name) values (167, 'Lyon');
insert into Cities (id, Name) values (168, 'Greensboro');
insert into Cities (id, Name) values (169, 'Vila Ribeiro');
insert into Cities (id, Name) values (170, 'Den Chai');
insert into Cities (id, Name) values (171, 'Manjiang');
insert into Cities (id, Name) values (172, 'Xinkai');
insert into Cities (id, Name) values (173, 'Rābigh');
insert into Cities (id, Name) values (174, 'Loikaw');
insert into Cities (id, Name) values (175, 'Gaoxu');
insert into Cities (id, Name) values (176, 'Saltsjö-Boo');
insert into Cities (id, Name) values (177, 'Aleg');
insert into Cities (id, Name) values (178, 'Limoges');
insert into Cities (id, Name) values (179, 'Vidyayevo');
insert into Cities (id, Name) values (180, 'Sandaowan');
insert into Cities (id, Name) values (181, 'Huangjingba');
insert into Cities (id, Name) values (182, 'Pocrí');
insert into Cities (id, Name) values (183, 'Hudong');
insert into Cities (id, Name) values (184, 'Gò Dầu');
insert into Cities (id, Name) values (185, 'Tapera');
insert into Cities (id, Name) values (186, 'Hankha');
insert into Cities (id, Name) values (187, 'Novyy');
insert into Cities (id, Name) values (188, 'Cilaja');
insert into Cities (id, Name) values (189, 'Tintina');
insert into Cities (id, Name) values (190, 'Peoria');
insert into Cities (id, Name) values (191, 'Sędziszów');
insert into Cities (id, Name) values (192, 'Vokhaïkó');
insert into Cities (id, Name) values (193, 'Tafí del Valle');
insert into Cities (id, Name) values (194, 'Ignalina');
insert into Cities (id, Name) values (195, 'Kapenguria');
insert into Cities (id, Name) values (196, 'Kedrovoye');
insert into Cities (id, Name) values (197, 'Amga');
insert into Cities (id, Name) values (198, 'Qo‘qon');
insert into Cities (id, Name) values (199, 'Zarechnyy');
insert into Cities (id, Name) values (200, 'Yuezhao');
insert into Cities (id, Name) values (201, 'Moppo');
insert into Cities (id, Name) values (202, 'Rosebank');
insert into Cities (id, Name) values (203, 'Ngulahan');
insert into Cities (id, Name) values (204, 'Sindangan');
insert into Cities (id, Name) values (205, 'Almeria');
insert into Cities (id, Name) values (206, 'Tomé');
insert into Cities (id, Name) values (207, 'Bobota');
insert into Cities (id, Name) values (208, 'Kosonsoy Shahri');
insert into Cities (id, Name) values (209, 'Sanxi');
insert into Cities (id, Name) values (210, 'Langkap');
insert into Cities (id, Name) values (211, 'Langádhia');
insert into Cities (id, Name) values (212, 'Ishige');
insert into Cities (id, Name) values (213, 'Taekas');
insert into Cities (id, Name) values (214, 'Gandra');
insert into Cities (id, Name) values (215, 'Rawannawi Village');
insert into Cities (id, Name) values (216, 'Non Suwan');
insert into Cities (id, Name) values (217, 'Qimeng');
insert into Cities (id, Name) values (218, 'Velká nad Veličkou');
insert into Cities (id, Name) values (219, 'Algés');
insert into Cities (id, Name) values (220, 'Tinawagan');
insert into Cities (id, Name) values (221, 'Selishche');
insert into Cities (id, Name) values (222, 'Cololaca');
insert into Cities (id, Name) values (223, 'Juhut');
insert into Cities (id, Name) values (224, 'Majia');
insert into Cities (id, Name) values (225, 'Żarów');
insert into Cities (id, Name) values (226, 'Shiye');
insert into Cities (id, Name) values (227, 'Wadung');
insert into Cities (id, Name) values (228, 'Bulog');
insert into Cities (id, Name) values (229, 'Quinta');
insert into Cities (id, Name) values (230, 'Radenković');
insert into Cities (id, Name) values (231, 'Kubachi');
insert into Cities (id, Name) values (232, 'Facatativá');
insert into Cities (id, Name) values (233, 'Arrepiado');
insert into Cities (id, Name) values (234, 'Wenping');
insert into Cities (id, Name) values (235, 'Vårby');
insert into Cities (id, Name) values (236, 'El Parco District');
insert into Cities (id, Name) values (237, 'Jingling');
insert into Cities (id, Name) values (238, 'Löddeköpinge');
insert into Cities (id, Name) values (239, 'Pakuncen');
insert into Cities (id, Name) values (240, 'Nowlamary');
insert into Cities (id, Name) values (241, 'Velké Losiny');
insert into Cities (id, Name) values (242, 'Montpellier');
insert into Cities (id, Name) values (243, 'Borzytuchom');
insert into Cities (id, Name) values (244, 'Pengfang');
insert into Cities (id, Name) values (245, 'Kabala');
insert into Cities (id, Name) values (246, 'Santo Antônio do Monte');
insert into Cities (id, Name) values (247, 'Lungmar');
insert into Cities (id, Name) values (248, 'Qishui');
insert into Cities (id, Name) values (249, 'Jindou');
insert into Cities (id, Name) values (250, 'Hexi');
insert into Cities (id, Name) values (251, 'Dongjiao');
insert into Cities (id, Name) values (252, 'Guanhães');
insert into Cities (id, Name) values (253, 'Vila Chã');
insert into Cities (id, Name) values (254, 'Tigbaw');
insert into Cities (id, Name) values (255, 'Tacarigua');
insert into Cities (id, Name) values (256, 'Kuhmoinen');
insert into Cities (id, Name) values (257, 'Nanyang');
insert into Cities (id, Name) values (258, 'Beiping');
insert into Cities (id, Name) values (259, 'Changcun');
insert into Cities (id, Name) values (260, 'Verkhozim');
insert into Cities (id, Name) values (261, 'Calvos');
insert into Cities (id, Name) values (262, 'Liulin');
insert into Cities (id, Name) values (263, 'Verkhniy Dashkesan');
insert into Cities (id, Name) values (264, 'Semarang');
insert into Cities (id, Name) values (265, 'Mādabā');
insert into Cities (id, Name) values (266, 'Sukarame');
insert into Cities (id, Name) values (267, 'Citeureup');
insert into Cities (id, Name) values (268, 'Andahuaylas');
insert into Cities (id, Name) values (269, 'La Paz');
insert into Cities (id, Name) values (270, 'Nanortalik');
insert into Cities (id, Name) values (271, 'Phú Vang');
insert into Cities (id, Name) values (272, 'Všestary');
insert into Cities (id, Name) values (273, 'Ikedachō');
insert into Cities (id, Name) values (274, 'Elektrėnai');
insert into Cities (id, Name) values (275, 'Erling');
insert into Cities (id, Name) values (276, 'Rennes');
insert into Cities (id, Name) values (277, 'Altan-Ovoo');
insert into Cities (id, Name) values (278, 'Jalinan');
insert into Cities (id, Name) values (279, 'Oroin Xibe');
insert into Cities (id, Name) values (280, 'Maanas');
insert into Cities (id, Name) values (281, 'Orichi');
insert into Cities (id, Name) values (282, 'Jiangshan');
insert into Cities (id, Name) values (283, 'San Vicente');
insert into Cities (id, Name) values (284, 'Liping');
insert into Cities (id, Name) values (285, 'Idrinskoye');
insert into Cities (id, Name) values (286, 'Miribel');
insert into Cities (id, Name) values (287, 'Ngurore');
insert into Cities (id, Name) values (288, 'Ringinrejo');
insert into Cities (id, Name) values (289, 'Stepanivka');
insert into Cities (id, Name) values (290, 'Agrelo');
insert into Cities (id, Name) values (291, 'Perístasi');
insert into Cities (id, Name) values (292, 'Lederaba');
insert into Cities (id, Name) values (293, 'Dolavón');
insert into Cities (id, Name) values (294, 'Rouen');
insert into Cities (id, Name) values (295, 'Ul');
insert into Cities (id, Name) values (296, 'Paamiut');
insert into Cities (id, Name) values (297, 'Cahuacho');
insert into Cities (id, Name) values (298, 'Xiekou');
insert into Cities (id, Name) values (299, 'Albertville');
insert into Cities (id, Name) values (300, 'Notodden');
insert into Cities (id, Name) values (301, 'Francistown');
insert into Cities (id, Name) values (302, 'Hà Tiên');
insert into Cities (id, Name) values (303, 'Hanshou');
insert into Cities (id, Name) values (304, 'Damiao');
insert into Cities (id, Name) values (305, 'Mnogoudobnoye');
insert into Cities (id, Name) values (306, 'Malhiao');
insert into Cities (id, Name) values (307, 'Pentéli');
insert into Cities (id, Name) values (308, 'Kedatuan');
insert into Cities (id, Name) values (309, 'Dijon');
insert into Cities (id, Name) values (310, 'Mytishchi');
insert into Cities (id, Name) values (311, 'Cergy-Pontoise');
insert into Cities (id, Name) values (312, 'Bilohirs’k');
insert into Cities (id, Name) values (313, 'Rychnov nad Kněžnou');
insert into Cities (id, Name) values (314, 'Sugihmukti');
insert into Cities (id, Name) values (315, 'Mala Danylivka');
insert into Cities (id, Name) values (316, 'Shikhazany');
insert into Cities (id, Name) values (317, 'Storozhevaya');
insert into Cities (id, Name) values (318, 'Siding');
insert into Cities (id, Name) values (319, 'Songjiang');
insert into Cities (id, Name) values (320, 'Oyabe');
insert into Cities (id, Name) values (321, 'Oepula');
insert into Cities (id, Name) values (322, 'Mamboma');
insert into Cities (id, Name) values (323, 'Karangtengah');
insert into Cities (id, Name) values (324, 'Stamáta');
insert into Cities (id, Name) values (325, 'Piggs Peak');
insert into Cities (id, Name) values (326, 'Adzopé');
insert into Cities (id, Name) values (327, 'Pader Palwo');
insert into Cities (id, Name) values (328, 'Bindang');
insert into Cities (id, Name) values (329, 'Chartres');
insert into Cities (id, Name) values (330, 'Kladno');
insert into Cities (id, Name) values (331, 'Bafoussam');
insert into Cities (id, Name) values (332, 'Casais Brancos');
insert into Cities (id, Name) values (333, 'Slunj');
insert into Cities (id, Name) values (334, 'Ḩabbān');
insert into Cities (id, Name) values (335, 'Brändö');
insert into Cities (id, Name) values (336, 'Quchi');
insert into Cities (id, Name) values (337, 'Villa Francisca');
insert into Cities (id, Name) values (338, 'Dubki');
insert into Cities (id, Name) values (339, 'Krông Kmar');
insert into Cities (id, Name) values (340, 'Iaçu');
insert into Cities (id, Name) values (341, 'Szprotawa');
insert into Cities (id, Name) values (342, 'Pimentel');
insert into Cities (id, Name) values (343, 'Uruaçu');
insert into Cities (id, Name) values (344, 'Zhaizigou');
insert into Cities (id, Name) values (345, 'Santa Fe');
insert into Cities (id, Name) values (346, 'Waipawa');
insert into Cities (id, Name) values (347, 'Baoyang');
insert into Cities (id, Name) values (348, 'Gaohu');
insert into Cities (id, Name) values (349, 'Sankoutang');
insert into Cities (id, Name) values (350, 'San Juan de Planes');
insert into Cities (id, Name) values (351, 'Cincinnati');
insert into Cities (id, Name) values (352, 'Río Ceballos');
insert into Cities (id, Name) values (353, 'Tunasbaru');
insert into Cities (id, Name) values (354, 'Dongting');
insert into Cities (id, Name) values (355, 'Hüremt');
insert into Cities (id, Name) values (356, 'Yanac');
insert into Cities (id, Name) values (357, 'Sojo');
insert into Cities (id, Name) values (358, 'Suwaluh');
insert into Cities (id, Name) values (359, 'Qārah');
insert into Cities (id, Name) values (360, 'Batabanó');
insert into Cities (id, Name) values (361, '‘Izbat al Burj');
insert into Cities (id, Name) values (362, 'Ogōri-shimogō');
insert into Cities (id, Name) values (363, 'Tielou');
insert into Cities (id, Name) values (364, 'Krasnaya Gorka');
insert into Cities (id, Name) values (365, 'Grand Rapids');
insert into Cities (id, Name) values (366, 'Bobai');
insert into Cities (id, Name) values (367, 'Kuala Terengganu');
insert into Cities (id, Name) values (368, 'Pingdong');
insert into Cities (id, Name) values (369, 'San-Pédro');
insert into Cities (id, Name) values (370, 'Talawi');
insert into Cities (id, Name) values (371, 'Sukamulia');
insert into Cities (id, Name) values (372, 'Berezivka');
insert into Cities (id, Name) values (373, 'Shuinan');
insert into Cities (id, Name) values (374, 'Hadayang');
insert into Cities (id, Name) values (375, 'Zeleneč');
insert into Cities (id, Name) values (376, 'Santa Maria Oliveira');
insert into Cities (id, Name) values (377, 'Kwangmyŏng');
insert into Cities (id, Name) values (378, 'Petrovice u Karviné');
insert into Cities (id, Name) values (379, 'Guinsadan');
insert into Cities (id, Name) values (380, 'Tashi');
insert into Cities (id, Name) values (381, 'Béziers');
insert into Cities (id, Name) values (382, 'Siemianowice Śląskie');
insert into Cities (id, Name) values (383, 'Leganes');
insert into Cities (id, Name) values (384, 'Tamel');
insert into Cities (id, Name) values (385, 'Alīgūdarz');
insert into Cities (id, Name) values (386, 'Zengjia');
insert into Cities (id, Name) values (387, 'Zaytā');
insert into Cities (id, Name) values (388, 'Bangil');
insert into Cities (id, Name) values (389, 'Sofiyivka');
insert into Cities (id, Name) values (390, 'Iaçu');
insert into Cities (id, Name) values (391, 'Załuski');
insert into Cities (id, Name) values (392, 'Karlskoga');
insert into Cities (id, Name) values (393, 'Narutochō-mitsuishi');
insert into Cities (id, Name) values (394, 'Granada');
insert into Cities (id, Name) values (395, 'Robonkon');
insert into Cities (id, Name) values (396, 'Muruni');
insert into Cities (id, Name) values (397, 'Kathu');
insert into Cities (id, Name) values (398, 'Anambongan');
insert into Cities (id, Name) values (399, 'Turbaco');
insert into Cities (id, Name) values (400, 'Palmeira');
insert into Cities (id, Name) values (401, 'Votkinsk');
insert into Cities (id, Name) values (402, 'Betong');
insert into Cities (id, Name) values (403, 'Puan');
insert into Cities (id, Name) values (404, 'Pacasmayo');
insert into Cities (id, Name) values (405, 'Blobo');
insert into Cities (id, Name) values (406, 'Panggunguni');
insert into Cities (id, Name) values (407, 'Diffa');
insert into Cities (id, Name) values (408, 'Stanowice');
insert into Cities (id, Name) values (409, 'Tielong');
insert into Cities (id, Name) values (410, 'Gandu');
insert into Cities (id, Name) values (411, 'Surovikino');
insert into Cities (id, Name) values (412, 'Xinghe Chengguanzhen');
insert into Cities (id, Name) values (413, 'Los Angeles');
insert into Cities (id, Name) values (414, 'Lewobelek');
insert into Cities (id, Name) values (415, 'Krzeszów');
insert into Cities (id, Name) values (416, 'Hucun');
insert into Cities (id, Name) values (417, 'Gaza');
insert into Cities (id, Name) values (418, 'Bełsznica');
insert into Cities (id, Name) values (419, 'Udanin');
insert into Cities (id, Name) values (420, 'Munse');
insert into Cities (id, Name) values (421, 'Eisen');
insert into Cities (id, Name) values (422, 'Calizo');
insert into Cities (id, Name) values (423, 'Yukou');
insert into Cities (id, Name) values (424, 'Saint-Maixent-l''École');
insert into Cities (id, Name) values (425, 'Akat Amnuai');
insert into Cities (id, Name) values (426, 'Kuala Pilah');
insert into Cities (id, Name) values (427, 'Banyuurip');
insert into Cities (id, Name) values (428, 'Gambang');
insert into Cities (id, Name) values (429, 'Watsa');
insert into Cities (id, Name) values (430, 'Tochio-honchō');
insert into Cities (id, Name) values (431, 'Yako');
insert into Cities (id, Name) values (432, 'Real');
insert into Cities (id, Name) values (433, 'Nueva Germania');
insert into Cities (id, Name) values (434, 'Shun’ga');
insert into Cities (id, Name) values (435, 'Santa Catarina Barahona');
insert into Cities (id, Name) values (436, 'Puerto Eldorado');
insert into Cities (id, Name) values (437, 'Fukayachō');
insert into Cities (id, Name) values (438, 'Odesskoye');
insert into Cities (id, Name) values (439, 'Niaojin');
insert into Cities (id, Name) values (440, '‘Eilabun');
insert into Cities (id, Name) values (441, 'Buritama');
insert into Cities (id, Name) values (442, 'Apodi');
insert into Cities (id, Name) values (443, 'Lebahseri');
insert into Cities (id, Name) values (444, 'Faaa');
insert into Cities (id, Name) values (445, 'Göteborg');
insert into Cities (id, Name) values (446, 'Aimorés');
insert into Cities (id, Name) values (447, 'Chilecito');
insert into Cities (id, Name) values (448, 'Folques');
insert into Cities (id, Name) values (449, 'Perjuangan');
insert into Cities (id, Name) values (450, 'Tampa');
insert into Cities (id, Name) values (451, 'Banjarmasin');
insert into Cities (id, Name) values (452, 'Seixas');
insert into Cities (id, Name) values (453, 'Binkolo');
insert into Cities (id, Name) values (454, 'Krasnyy Profintern');
insert into Cities (id, Name) values (455, 'Kiboga');
insert into Cities (id, Name) values (456, 'Spas-Zaulok');
insert into Cities (id, Name) values (457, 'Thiais');
insert into Cities (id, Name) values (458, 'Montenegro');
insert into Cities (id, Name) values (459, 'Enhe Hada');
insert into Cities (id, Name) values (460, 'Huddinge');
insert into Cities (id, Name) values (461, 'Santa Rosa');
insert into Cities (id, Name) values (462, 'Bamban');
insert into Cities (id, Name) values (463, 'Hats’avan');
insert into Cities (id, Name) values (464, 'Borås');
insert into Cities (id, Name) values (465, 'Mloko');
insert into Cities (id, Name) values (466, 'Igreja');
insert into Cities (id, Name) values (467, 'Tetyushi');
insert into Cities (id, Name) values (468, 'Mawu');
insert into Cities (id, Name) values (469, 'Rāwandūz');
insert into Cities (id, Name) values (470, 'Wiphawadi');
insert into Cities (id, Name) values (471, 'Xinzhai');
insert into Cities (id, Name) values (472, 'La Rioja');
insert into Cities (id, Name) values (473, 'Duqu');
insert into Cities (id, Name) values (474, 'Évry');
insert into Cities (id, Name) values (475, 'Gulou');
insert into Cities (id, Name) values (476, 'Caldelas');
insert into Cities (id, Name) values (477, 'Pingshui');
insert into Cities (id, Name) values (478, 'Baykonyr');
insert into Cities (id, Name) values (479, 'Leshukonskoye');
insert into Cities (id, Name) values (480, 'Telmin Suma');
insert into Cities (id, Name) values (481, 'Ganxi');
insert into Cities (id, Name) values (482, 'Bang Racham');
insert into Cities (id, Name) values (483, 'Jialou');
insert into Cities (id, Name) values (484, 'Bílovice');
insert into Cities (id, Name) values (485, 'Łopuszno');
insert into Cities (id, Name) values (486, 'Budta');
insert into Cities (id, Name) values (487, 'Gawul');
insert into Cities (id, Name) values (488, 'Yedogon');
insert into Cities (id, Name) values (489, 'Jeremi');
insert into Cities (id, Name) values (490, 'Santo António da Charneca');
insert into Cities (id, Name) values (491, 'Mizur');
insert into Cities (id, Name) values (492, 'Siteía');
insert into Cities (id, Name) values (493, 'Żernica');
insert into Cities (id, Name) values (494, 'Irshava');
insert into Cities (id, Name) values (495, 'Torsås');
insert into Cities (id, Name) values (496, 'Bajia');
insert into Cities (id, Name) values (497, 'Yunxiang');
insert into Cities (id, Name) values (498, 'Xiaojin');
insert into Cities (id, Name) values (499, 'Fanzhen');
insert into Cities (id, Name) values (500, 'Březová');
insert into Cities (id, Name) values (501, 'Langkapcaang Hilir');
insert into Cities (id, Name) values (502, 'Khorixas');
insert into Cities (id, Name) values (503, 'Pruzhany');
insert into Cities (id, Name) values (504, 'Obršani');
insert into Cities (id, Name) values (505, 'Końskowola');
insert into Cities (id, Name) values (506, 'Bol’shaya Setun’');
insert into Cities (id, Name) values (507, 'Viçosa');
insert into Cities (id, Name) values (508, 'Panjerrejo');
insert into Cities (id, Name) values (509, 'Krikil');
insert into Cities (id, Name) values (510, 'Spitak');
insert into Cities (id, Name) values (511, 'Chapultepec');
insert into Cities (id, Name) values (512, 'Nyrob');
insert into Cities (id, Name) values (513, 'Allanridge');
insert into Cities (id, Name) values (514, 'Taganrog');
insert into Cities (id, Name) values (515, 'Klang');
insert into Cities (id, Name) values (516, 'Sipirok');
insert into Cities (id, Name) values (517, 'Somerset East');
insert into Cities (id, Name) values (518, 'Diamantina');
insert into Cities (id, Name) values (519, 'Mosteiro');
insert into Cities (id, Name) values (520, 'Midland');
insert into Cities (id, Name) values (521, 'Joconal');
insert into Cities (id, Name) values (522, 'Vaggeryd');
insert into Cities (id, Name) values (523, 'Gaoqiao');
insert into Cities (id, Name) values (524, 'União');
insert into Cities (id, Name) values (525, 'Orissaare');
insert into Cities (id, Name) values (526, 'Uryupinsk');
insert into Cities (id, Name) values (527, 'Kacangan Lor');
insert into Cities (id, Name) values (528, 'Zhangping');
insert into Cities (id, Name) values (529, 'Limoges');
insert into Cities (id, Name) values (530, 'Sirnasari');
insert into Cities (id, Name) values (531, 'Pavlodar');
insert into Cities (id, Name) values (532, 'Tapera');
insert into Cities (id, Name) values (533, 'Alexandria');
insert into Cities (id, Name) values (534, 'Mandalgovi');
insert into Cities (id, Name) values (535, 'Dagu');
insert into Cities (id, Name) values (536, 'Taklale');
insert into Cities (id, Name) values (537, 'Bagneux');
insert into Cities (id, Name) values (538, 'Markaz Bilād aţ Ţa‘ām');
insert into Cities (id, Name) values (539, 'Ningmute');
insert into Cities (id, Name) values (540, 'Al Mushannaf');
insert into Cities (id, Name) values (541, 'Bujumbura');
insert into Cities (id, Name) values (542, 'Sipe Sipe');
insert into Cities (id, Name) values (543, 'Balykchy');
insert into Cities (id, Name) values (544, 'Viligili');
insert into Cities (id, Name) values (545, 'Marseille');
insert into Cities (id, Name) values (546, 'Shuanggang');
insert into Cities (id, Name) values (547, 'Solna');
insert into Cities (id, Name) values (548, 'Cortes');
insert into Cities (id, Name) values (549, 'Antananarivo');
insert into Cities (id, Name) values (550, 'Yangmadao');
insert into Cities (id, Name) values (551, 'Uppsala');
insert into Cities (id, Name) values (552, 'Mabasa');
insert into Cities (id, Name) values (553, 'Piotrków Kujawski');
insert into Cities (id, Name) values (554, 'Phuket');
insert into Cities (id, Name) values (555, 'Izborsk');
insert into Cities (id, Name) values (556, 'Sujiatun');
insert into Cities (id, Name) values (557, 'Hanyū');
insert into Cities (id, Name) values (558, 'Wiphawadi');
insert into Cities (id, Name) values (559, 'Hongqi');
insert into Cities (id, Name) values (560, 'Añelo');
insert into Cities (id, Name) values (561, 'Guiglo');
insert into Cities (id, Name) values (562, 'Siilinjärvi');
insert into Cities (id, Name) values (563, 'Tuapukan');
insert into Cities (id, Name) values (564, 'Langgapayung');
insert into Cities (id, Name) values (565, 'Malabar');
insert into Cities (id, Name) values (566, 'Chemin Grenier');
insert into Cities (id, Name) values (567, 'Tiglauigan');
insert into Cities (id, Name) values (568, 'Wuchagou');
insert into Cities (id, Name) values (569, 'Kampungruweh');
insert into Cities (id, Name) values (570, 'Villa Santa Rosa');
insert into Cities (id, Name) values (571, 'Cholet');
insert into Cities (id, Name) values (572, 'New Leyte');
insert into Cities (id, Name) values (573, 'Zhujiang');
insert into Cities (id, Name) values (574, 'Omoa');
insert into Cities (id, Name) values (575, 'Faro');
insert into Cities (id, Name) values (576, 'Waishan');
insert into Cities (id, Name) values (577, 'Paris 13');
insert into Cities (id, Name) values (578, 'Río Campo');
insert into Cities (id, Name) values (579, 'Legaspi');
insert into Cities (id, Name) values (580, 'Kalianyar Selatan');
insert into Cities (id, Name) values (581, 'Koło');
insert into Cities (id, Name) values (582, 'Pira');
insert into Cities (id, Name) values (583, 'Eirunepé');
insert into Cities (id, Name) values (584, 'Nabīnagar');
insert into Cities (id, Name) values (585, 'Cherëmukhovo');
insert into Cities (id, Name) values (586, 'Cambuí');
insert into Cities (id, Name) values (587, 'Shiyang');
insert into Cities (id, Name) values (588, 'Cuito');
insert into Cities (id, Name) values (589, 'Oskarshamn');
insert into Cities (id, Name) values (590, 'Nova Olímpia');
insert into Cities (id, Name) values (591, 'Zhihe');
insert into Cities (id, Name) values (592, 'Anju');
insert into Cities (id, Name) values (593, 'Matsudo');
insert into Cities (id, Name) values (594, 'Kuleqi');
insert into Cities (id, Name) values (595, 'Yanweigang');
insert into Cities (id, Name) values (596, 'Putre');
insert into Cities (id, Name) values (597, 'Quba');
insert into Cities (id, Name) values (598, 'Genova');
insert into Cities (id, Name) values (599, 'Shestakovo');
insert into Cities (id, Name) values (600, 'Lisewo Malborskie');
insert into Cities (id, Name) values (601, 'San Carlos');
insert into Cities (id, Name) values (602, 'Kotabaru');
insert into Cities (id, Name) values (603, 'Uppsala');
insert into Cities (id, Name) values (604, 'Luntas');
insert into Cities (id, Name) values (605, 'Savigny-le-Temple');
insert into Cities (id, Name) values (606, 'Toronto');
insert into Cities (id, Name) values (607, 'Qarqaraly');
insert into Cities (id, Name) values (608, 'Ćuprija');
insert into Cities (id, Name) values (609, 'Pailiao');
insert into Cities (id, Name) values (610, 'Chang’an');
insert into Cities (id, Name) values (611, 'Le Blanc-Mesnil');
insert into Cities (id, Name) values (612, 'Baltimore');
insert into Cities (id, Name) values (613, 'Kembangkerang Lauk Timur');
insert into Cities (id, Name) values (614, 'Kotabaru');
insert into Cities (id, Name) values (615, 'Guidong Chengguanzhen');
insert into Cities (id, Name) values (616, 'Pajarillo');
insert into Cities (id, Name) values (617, 'Anseong');
insert into Cities (id, Name) values (618, 'Bongsri');
insert into Cities (id, Name) values (619, 'Wangzha');
insert into Cities (id, Name) values (620, 'Huancabamba');
insert into Cities (id, Name) values (621, 'Amaraji');
insert into Cities (id, Name) values (622, 'Ban Talat Nua');
insert into Cities (id, Name) values (623, 'Viraco');
insert into Cities (id, Name) values (624, 'Kalahang');
insert into Cities (id, Name) values (625, 'Yuezhao');
insert into Cities (id, Name) values (626, 'Cuiabá');
insert into Cities (id, Name) values (627, 'Kokkini Trimithia');
insert into Cities (id, Name) values (628, 'Xambabazar');
insert into Cities (id, Name) values (629, 'Perbaungan');
insert into Cities (id, Name) values (630, 'Xincun');
insert into Cities (id, Name) values (631, 'Bandjoun');
insert into Cities (id, Name) values (632, 'Lakkíon');
insert into Cities (id, Name) values (633, 'Ouzini');
insert into Cities (id, Name) values (634, 'Xiaoruo');
insert into Cities (id, Name) values (635, 'Yaojiagou');
insert into Cities (id, Name) values (636, 'Fuxin');
insert into Cities (id, Name) values (637, 'Washington');
insert into Cities (id, Name) values (638, 'Dazu');
insert into Cities (id, Name) values (639, 'Yefremov');
insert into Cities (id, Name) values (640, 'Panyindangan');
insert into Cities (id, Name) values (641, 'Volgorechensk');
insert into Cities (id, Name) values (642, 'Roissy Charles-de-Gaulle');
insert into Cities (id, Name) values (643, 'Madison');
insert into Cities (id, Name) values (644, 'Nampula');
insert into Cities (id, Name) values (645, 'Mburukullu');
insert into Cities (id, Name) values (646, 'Grojec');
insert into Cities (id, Name) values (647, 'San Antonio');
insert into Cities (id, Name) values (648, 'Gourcy');
insert into Cities (id, Name) values (649, 'Pelem');
insert into Cities (id, Name) values (650, 'Matamey');
insert into Cities (id, Name) values (651, 'Dmytrivka');
insert into Cities (id, Name) values (652, 'El Crucero');
insert into Cities (id, Name) values (653, 'Potosí');
insert into Cities (id, Name) values (654, 'Vidyayevo');
insert into Cities (id, Name) values (655, 'Stříbro');
insert into Cities (id, Name) values (656, 'La Maná');
insert into Cities (id, Name) values (657, 'Pinheiro');
insert into Cities (id, Name) values (658, 'Sel’tso');
insert into Cities (id, Name) values (659, 'Vesele');
insert into Cities (id, Name) values (660, 'Rokitno Szlacheckie');
insert into Cities (id, Name) values (661, 'Yuewan');
insert into Cities (id, Name) values (662, 'Asopós');
insert into Cities (id, Name) values (663, 'Nakhabino');
insert into Cities (id, Name) values (664, 'Milano');
insert into Cities (id, Name) values (665, 'Jardoeira');
insert into Cities (id, Name) values (666, 'Coromandel');
insert into Cities (id, Name) values (667, 'Brodósqui');
insert into Cities (id, Name) values (668, 'Gilin');
insert into Cities (id, Name) values (669, 'Annau');
insert into Cities (id, Name) values (670, 'Pires do Rio');
insert into Cities (id, Name) values (671, 'Shimeitang');
insert into Cities (id, Name) values (672, 'Lambton Shores');
insert into Cities (id, Name) values (673, 'Otacílio Costa');
insert into Cities (id, Name) values (674, 'Stalowa Wola');
insert into Cities (id, Name) values (675, 'Yanas');
insert into Cities (id, Name) values (676, 'Long Thành');
insert into Cities (id, Name) values (677, 'Bù Đốp');
insert into Cities (id, Name) values (678, 'Skellefteå');
insert into Cities (id, Name) values (679, 'Gasri');
insert into Cities (id, Name) values (680, 'Lanshan');
insert into Cities (id, Name) values (681, 'San Francisco');
insert into Cities (id, Name) values (682, 'Zhaxi');
insert into Cities (id, Name) values (683, 'Manika');
insert into Cities (id, Name) values (684, 'Bisert’');
insert into Cities (id, Name) values (685, 'Sosnytsya');
insert into Cities (id, Name) values (686, 'Bianzhuang');
insert into Cities (id, Name) values (687, 'Gununggoong');
insert into Cities (id, Name) values (688, 'Épinal');
insert into Cities (id, Name) values (689, 'Hamilton');
insert into Cities (id, Name) values (690, 'Fengmu');
insert into Cities (id, Name) values (691, 'Vykhino-Zhulebino');
insert into Cities (id, Name) values (692, 'Kavallári');
insert into Cities (id, Name) values (693, 'Beixiang');
insert into Cities (id, Name) values (694, 'Huangyang');
insert into Cities (id, Name) values (695, 'Changma');
insert into Cities (id, Name) values (696, 'Martin');
insert into Cities (id, Name) values (697, 'Jiuzhen');
insert into Cities (id, Name) values (698, 'Düsseldorf');
insert into Cities (id, Name) values (699, 'Wuhu');
insert into Cities (id, Name) values (700, 'Xialu');
insert into Cities (id, Name) values (701, 'Stuttgart Stuttgart-Mitte');
insert into Cities (id, Name) values (702, 'Wutong');
insert into Cities (id, Name) values (703, 'Harstad');
insert into Cities (id, Name) values (704, 'Puan');
insert into Cities (id, Name) values (705, 'Ban Selaphum');
insert into Cities (id, Name) values (706, 'Strasbourg');
insert into Cities (id, Name) values (707, 'Alicante/Alacant');
insert into Cities (id, Name) values (708, 'Asahi');
insert into Cities (id, Name) values (709, 'Longkali');
insert into Cities (id, Name) values (710, 'Gurlan');
insert into Cities (id, Name) values (711, 'Zheleznogorsk-Ilimskiy');
insert into Cities (id, Name) values (712, 'Ar Ramthā');
insert into Cities (id, Name) values (713, 'Jinggan');
insert into Cities (id, Name) values (714, 'Thākurgaon');
insert into Cities (id, Name) values (715, 'Amangarh');
insert into Cities (id, Name) values (716, 'Iracemápolis');
insert into Cities (id, Name) values (717, 'Aloleng');
insert into Cities (id, Name) values (718, 'Tsévié');
insert into Cities (id, Name) values (719, 'Sioah');
insert into Cities (id, Name) values (720, 'Caitang');
insert into Cities (id, Name) values (721, 'Zehak');
insert into Cities (id, Name) values (722, 'Curepipe');
insert into Cities (id, Name) values (723, 'Dieppe');
insert into Cities (id, Name) values (724, 'Palmerston North');
insert into Cities (id, Name) values (725, 'Kunri');
insert into Cities (id, Name) values (726, 'San Carlos');
insert into Cities (id, Name) values (727, 'Anniston');
insert into Cities (id, Name) values (728, 'Xinan');
insert into Cities (id, Name) values (729, 'Krasica');
insert into Cities (id, Name) values (730, 'Independencia');
insert into Cities (id, Name) values (731, 'Charlotte');
insert into Cities (id, Name) values (732, 'Osypenko');
insert into Cities (id, Name) values (733, 'Quảng Yên');
insert into Cities (id, Name) values (734, 'Perzów');
insert into Cities (id, Name) values (735, 'Luthu');
insert into Cities (id, Name) values (736, 'Yingjiang');
insert into Cities (id, Name) values (737, 'Yongning');
insert into Cities (id, Name) values (738, 'Jingyu');
insert into Cities (id, Name) values (739, 'Bojnik');
insert into Cities (id, Name) values (740, 'El Corozal');
insert into Cities (id, Name) values (741, 'Žleby');
insert into Cities (id, Name) values (742, 'Tortosa');
insert into Cities (id, Name) values (743, 'Voiron');
insert into Cities (id, Name) values (744, 'Nassau');
insert into Cities (id, Name) values (745, 'Montpellier');
insert into Cities (id, Name) values (746, 'Lapaz');
insert into Cities (id, Name) values (747, 'Camasca');
insert into Cities (id, Name) values (748, 'Pierreville');
insert into Cities (id, Name) values (749, 'Duanjia');
insert into Cities (id, Name) values (750, 'Ash Sharyah');
insert into Cities (id, Name) values (751, 'Darenzhuang');
insert into Cities (id, Name) values (752, 'Hanfeng');
insert into Cities (id, Name) values (753, 'Antaparco');
insert into Cities (id, Name) values (754, 'Águas Belas');
insert into Cities (id, Name) values (755, 'Sifangxi');
insert into Cities (id, Name) values (756, 'Tiepu');
insert into Cities (id, Name) values (757, 'Piran');
insert into Cities (id, Name) values (758, 'Tilburg');
insert into Cities (id, Name) values (759, 'Mramani');
insert into Cities (id, Name) values (760, 'Velyka Mykhaylivka');
insert into Cities (id, Name) values (761, 'Vallehermoso');
insert into Cities (id, Name) values (762, 'San Lucas');
insert into Cities (id, Name) values (763, 'Kaizuka');
insert into Cities (id, Name) values (764, 'Villach');
insert into Cities (id, Name) values (765, 'Wang Sam Mo');
insert into Cities (id, Name) values (766, 'Bełsznica');
insert into Cities (id, Name) values (767, 'Soledad');
insert into Cities (id, Name) values (768, 'Xinzhou');
insert into Cities (id, Name) values (769, 'Kopstal');
insert into Cities (id, Name) values (770, 'Talok');
insert into Cities (id, Name) values (771, 'Muarapinang');
insert into Cities (id, Name) values (772, 'Paraguaçu Paulista');
insert into Cities (id, Name) values (773, 'Takahashi');
insert into Cities (id, Name) values (774, 'Verkhniye Achaluki');
insert into Cities (id, Name) values (775, 'Yi’an');
insert into Cities (id, Name) values (776, 'Tlogosari');
insert into Cities (id, Name) values (777, 'Zaprudnya');
insert into Cities (id, Name) values (778, 'Talisay');
insert into Cities (id, Name) values (779, 'Baleal');
insert into Cities (id, Name) values (780, 'Vanderbijlpark');
insert into Cities (id, Name) values (781, 'Castanhal');
insert into Cities (id, Name) values (782, 'Água Preta');
insert into Cities (id, Name) values (783, 'Cruz das Almas');
insert into Cities (id, Name) values (784, 'Thị Trấn Phù Yên');
insert into Cities (id, Name) values (785, 'Ta Khmau');
insert into Cities (id, Name) values (786, 'Karangintan');
insert into Cities (id, Name) values (787, 'Cabatuan');
insert into Cities (id, Name) values (788, 'Ko Si Chang');
insert into Cities (id, Name) values (789, 'Binkolo');
insert into Cities (id, Name) values (790, 'Phatthalung');
insert into Cities (id, Name) values (791, 'Bochov');
insert into Cities (id, Name) values (792, 'Watergrasshill');
insert into Cities (id, Name) values (793, 'Randu');
insert into Cities (id, Name) values (794, 'Naji');
insert into Cities (id, Name) values (795, 'Tandou');
insert into Cities (id, Name) values (796, 'Barwałd Górny');
insert into Cities (id, Name) values (797, 'Vale de Figueira');
insert into Cities (id, Name) values (798, 'Cigebrok');
insert into Cities (id, Name) values (799, 'Żebbuġ');
insert into Cities (id, Name) values (800, 'Alebtong');
insert into Cities (id, Name) values (801, 'Francisco J Mujica');
insert into Cities (id, Name) values (802, 'Zhelin');
insert into Cities (id, Name) values (803, 'El Bolsón');
insert into Cities (id, Name) values (804, 'Benavila');
insert into Cities (id, Name) values (805, 'Bayshint');
insert into Cities (id, Name) values (806, 'Binafun');
insert into Cities (id, Name) values (807, 'Kybartai');
insert into Cities (id, Name) values (808, 'Mao’ershan');
insert into Cities (id, Name) values (809, 'Houyu');
insert into Cities (id, Name) values (810, 'Loma Bonita');
insert into Cities (id, Name) values (811, 'Guaranda');
insert into Cities (id, Name) values (812, 'Djounie');
insert into Cities (id, Name) values (813, 'Oslo');
insert into Cities (id, Name) values (814, 'Yanhe');
insert into Cities (id, Name) values (815, 'Puteran Kidul');
insert into Cities (id, Name) values (816, 'Sendang');
insert into Cities (id, Name) values (817, 'Patalan');
insert into Cities (id, Name) values (818, 'Yanghuxiang');
insert into Cities (id, Name) values (819, 'Heling');
insert into Cities (id, Name) values (820, 'Paris 12');
insert into Cities (id, Name) values (821, 'Carcavelos');
insert into Cities (id, Name) values (822, 'Mosina');
insert into Cities (id, Name) values (823, 'Capâo Bonito');
insert into Cities (id, Name) values (824, 'Babakan');
insert into Cities (id, Name) values (825, 'Zhongdong');
insert into Cities (id, Name) values (826, 'Mora');
insert into Cities (id, Name) values (827, 'Chãos');
insert into Cities (id, Name) values (828, 'Nankou');
insert into Cities (id, Name) values (829, 'Chenghuang');
insert into Cities (id, Name) values (830, 'Ubaitaba');
insert into Cities (id, Name) values (831, 'Mapiripán');
insert into Cities (id, Name) values (832, 'Tembol');
insert into Cities (id, Name) values (833, 'Arbaoua');
insert into Cities (id, Name) values (834, 'Ungus-Ungus');
insert into Cities (id, Name) values (835, 'Tawan tawan');
insert into Cities (id, Name) values (836, 'Mabilog');
insert into Cities (id, Name) values (837, 'Kuala Lumpur');
insert into Cities (id, Name) values (838, 'Saransk');
insert into Cities (id, Name) values (839, 'Chợ Mới');
insert into Cities (id, Name) values (840, 'San Antonio');
insert into Cities (id, Name) values (841, 'Aleksotas');
insert into Cities (id, Name) values (842, 'Mandangoa');
insert into Cities (id, Name) values (843, 'Spiczyn');
insert into Cities (id, Name) values (844, 'Port-Gentil');
insert into Cities (id, Name) values (845, 'Gabahan');
insert into Cities (id, Name) values (846, 'Vareiá');
insert into Cities (id, Name) values (847, 'Litibakul');
insert into Cities (id, Name) values (848, 'Mshinskaya');
insert into Cities (id, Name) values (849, 'Huaping');
insert into Cities (id, Name) values (850, 'Kashihara');
insert into Cities (id, Name) values (851, 'Victoriaville');
insert into Cities (id, Name) values (852, 'Hekinan');
insert into Cities (id, Name) values (853, 'Aţ Ţaybah');
insert into Cities (id, Name) values (854, 'Ngadri');
insert into Cities (id, Name) values (855, 'Briceni');
insert into Cities (id, Name) values (856, 'Järfälla');
insert into Cities (id, Name) values (857, 'Najiaying');
insert into Cities (id, Name) values (858, 'Aldergrove');
insert into Cities (id, Name) values (859, 'Mbandaka');
insert into Cities (id, Name) values (860, 'Caçapava do Sul');
insert into Cities (id, Name) values (861, 'Kacha');
insert into Cities (id, Name) values (862, 'Svenljunga');
insert into Cities (id, Name) values (863, 'Bei');
insert into Cities (id, Name) values (864, 'Piraju');
insert into Cities (id, Name) values (865, 'Catabola');
insert into Cities (id, Name) values (866, 'Ōdachō-ōda');
insert into Cities (id, Name) values (867, 'Banaran');
insert into Cities (id, Name) values (868, 'Koukkuniemi');
insert into Cities (id, Name) values (869, 'Randudongkal');
insert into Cities (id, Name) values (870, 'Koubia');
insert into Cities (id, Name) values (871, 'Plovdiv');
insert into Cities (id, Name) values (872, 'Sandefjord');
insert into Cities (id, Name) values (873, 'San Miguelito');
insert into Cities (id, Name) values (874, 'Mertert');
insert into Cities (id, Name) values (875, 'Nova Odessa');
insert into Cities (id, Name) values (876, 'Oxelösund');
insert into Cities (id, Name) values (877, 'Popayán');
insert into Cities (id, Name) values (878, 'Oslo');
insert into Cities (id, Name) values (879, 'Xiaomian');
insert into Cities (id, Name) values (880, 'Juhaynah');
insert into Cities (id, Name) values (881, 'Huolongping');
insert into Cities (id, Name) values (882, 'Tanahmerah');
insert into Cities (id, Name) values (883, 'Glendale');
insert into Cities (id, Name) values (884, 'Bunga Mas');
insert into Cities (id, Name) values (885, 'Banī Walīd');
insert into Cities (id, Name) values (886, 'Jixiang');
insert into Cities (id, Name) values (887, 'Ramotswa');
insert into Cities (id, Name) values (888, 'Rájec-Jestřebí');
insert into Cities (id, Name) values (889, 'Paghmān');
insert into Cities (id, Name) values (890, 'Molsheim');
insert into Cities (id, Name) values (891, 'Bastos');
insert into Cities (id, Name) values (892, 'Kŭlob');
insert into Cities (id, Name) values (893, 'Joliet');
insert into Cities (id, Name) values (894, 'El Fasher');
insert into Cities (id, Name) values (895, 'Jesenice');
insert into Cities (id, Name) values (896, 'Carcassonne');
insert into Cities (id, Name) values (897, 'Pamoyanan');
insert into Cities (id, Name) values (898, 'Pau');
insert into Cities (id, Name) values (899, 'Yongfeng');
insert into Cities (id, Name) values (900, 'Chacabuco');
insert into Cities (id, Name) values (901, 'Utmānzai');
insert into Cities (id, Name) values (902, 'Tiancheng');
insert into Cities (id, Name) values (903, 'Magallanes');
insert into Cities (id, Name) values (904, 'Middelburg');
insert into Cities (id, Name) values (905, 'Mlawe');
insert into Cities (id, Name) values (906, 'Klole');
insert into Cities (id, Name) values (907, 'Talas');
insert into Cities (id, Name) values (908, 'Kostrzyn nad Odrą');
insert into Cities (id, Name) values (909, 'Järfälla');
insert into Cities (id, Name) values (910, 'Sangba');
insert into Cities (id, Name) values (911, 'San Juan');
insert into Cities (id, Name) values (912, 'Karema');
insert into Cities (id, Name) values (913, 'Sukasari');
insert into Cities (id, Name) values (914, 'Göteborg');
insert into Cities (id, Name) values (915, 'Neftegorsk');
insert into Cities (id, Name) values (916, 'Si Narong');
insert into Cities (id, Name) values (917, 'Vishow');
insert into Cities (id, Name) values (918, 'Övertorneå');
insert into Cities (id, Name) values (919, 'Itsandzéni');
insert into Cities (id, Name) values (920, 'Horka nad Moravou');
insert into Cities (id, Name) values (921, 'Kopstal');
insert into Cities (id, Name) values (922, 'Mosetse');
insert into Cities (id, Name) values (923, 'Tijucas');
insert into Cities (id, Name) values (924, 'Lop Buri');
insert into Cities (id, Name) values (925, 'Yashikera');
insert into Cities (id, Name) values (926, 'Nanterre');
insert into Cities (id, Name) values (927, 'Shitan');
insert into Cities (id, Name) values (928, 'Yunluo');
insert into Cities (id, Name) values (929, 'Tianqian');
insert into Cities (id, Name) values (930, 'Trebisht-Muçinë');
insert into Cities (id, Name) values (931, 'Lendava');
insert into Cities (id, Name) values (932, 'Zelenogorsk');
insert into Cities (id, Name) values (933, 'Detroit');
insert into Cities (id, Name) values (934, 'Lerum');
insert into Cities (id, Name) values (935, 'Guadalupe');
insert into Cities (id, Name) values (936, 'Purworejo');
insert into Cities (id, Name) values (937, 'Ruoqiang');
insert into Cities (id, Name) values (938, 'Guitang');
insert into Cities (id, Name) values (939, 'Xiejia');
insert into Cities (id, Name) values (940, 'Pengwan');
insert into Cities (id, Name) values (941, 'Shimen');
insert into Cities (id, Name) values (942, 'Huangnihe');
insert into Cities (id, Name) values (943, 'Bayan-Ovoo');
insert into Cities (id, Name) values (944, 'Khemisset');
insert into Cities (id, Name) values (945, 'Cariaco');
insert into Cities (id, Name) values (946, 'Zouparria do Monte');
insert into Cities (id, Name) values (947, 'Desa Nasol');
insert into Cities (id, Name) values (948, 'Sabana Grande');
insert into Cities (id, Name) values (949, 'Kiviõli');
insert into Cities (id, Name) values (950, 'Mateur');
insert into Cities (id, Name) values (951, 'Bordeaux');
insert into Cities (id, Name) values (952, 'Kaesŏng');
insert into Cities (id, Name) values (953, 'Santana');
insert into Cities (id, Name) values (954, 'Heshang');
insert into Cities (id, Name) values (955, 'Xuefu');
insert into Cities (id, Name) values (956, 'Praga Północ');
insert into Cities (id, Name) values (957, 'Nueva Guinea');
insert into Cities (id, Name) values (958, 'Pingdi');
insert into Cities (id, Name) values (959, 'Kista');
insert into Cities (id, Name) values (960, 'Kakegawa');
insert into Cities (id, Name) values (961, 'Gubskaya');
insert into Cities (id, Name) values (962, 'Aija');
insert into Cities (id, Name) values (963, 'Chom Bueng');
insert into Cities (id, Name) values (964, 'Shuanglong');
insert into Cities (id, Name) values (965, 'Charleston');
insert into Cities (id, Name) values (966, 'Domsjö');
insert into Cities (id, Name) values (967, 'Tonghu');
insert into Cities (id, Name) values (968, 'Vinsady');
insert into Cities (id, Name) values (969, 'Jequié');
insert into Cities (id, Name) values (970, 'Além do Rio');
insert into Cities (id, Name) values (971, 'Dasha');
insert into Cities (id, Name) values (972, 'Xiaopu');
insert into Cities (id, Name) values (973, 'Wushi');
insert into Cities (id, Name) values (974, 'Além');
insert into Cities (id, Name) values (975, 'Taosha');
insert into Cities (id, Name) values (976, 'Krajan Karangwage');
insert into Cities (id, Name) values (977, 'Calape');
insert into Cities (id, Name) values (978, 'Paris 03');
insert into Cities (id, Name) values (979, 'Magersari');
insert into Cities (id, Name) values (980, 'Nanmu');
insert into Cities (id, Name) values (981, 'Wysoka');
insert into Cities (id, Name) values (982, 'Stockholm');
insert into Cities (id, Name) values (983, 'Yeysk');
insert into Cities (id, Name) values (984, 'Nūrābād');
insert into Cities (id, Name) values (985, 'Granja');
insert into Cities (id, Name) values (986, 'Cogreg Wetan');
insert into Cities (id, Name) values (987, 'Nomhon');
insert into Cities (id, Name) values (988, 'Yur’yevets');
insert into Cities (id, Name) values (989, 'Jiangkou');
insert into Cities (id, Name) values (990, 'Nuwaybi‘a');
insert into Cities (id, Name) values (991, 'Dujuuma');
insert into Cities (id, Name) values (992, 'Calceta');
insert into Cities (id, Name) values (993, 'Hato Mayor del Rey');
insert into Cities (id, Name) values (994, 'Sabbah');
insert into Cities (id, Name) values (995, 'Yongfeng');
insert into Cities (id, Name) values (996, 'Aībak');
insert into Cities (id, Name) values (997, 'Grytviken');
insert into Cities (id, Name) values (998, 'Massaranduba');
insert into Cities (id, Name) values (999, 'Quinta dos Frades');
insert into Cities (id, Name) values (1000, 'El Coco');
