insert into Streets (id, Name) values (1, 'Dapin');
insert into Streets (id, Name) values (2, 'Dapin');
insert into Streets (id, Name) values (3, 'Kingsford');
insert into Streets (id, Name) values (4, 'La Follette');
insert into Streets (id, Name) values (5, 'Algoma');
insert into Streets (id, Name) values (6, 'Ryan');
insert into Streets (id, Name) values (7, 'Coolidge');
insert into Streets (id, Name) values (8, 'Maywood');
insert into Streets (id, Name) values (9, 'South');
insert into Streets (id, Name) values (10, 'Morning');
insert into Streets (id, Name) values (11, 'Barby');
insert into Streets (id, Name) values (12, 'Stone Corner');
insert into Streets (id, Name) values (13, 'Spohn');
insert into Streets (id, Name) values (14, 'Myrtle');
insert into Streets (id, Name) values (15, 'Dennis');
insert into Streets (id, Name) values (16, 'Holy Cross');
insert into Streets (id, Name) values (17, 'Victoria');
insert into Streets (id, Name) values (18, 'Tennessee');
insert into Streets (id, Name) values (19, 'Merchant');
insert into Streets (id, Name) values (20, 'Shopko');
insert into Streets (id, Name) values (21, 'Quincy');
insert into Streets (id, Name) values (22, 'Schurz');
insert into Streets (id, Name) values (23, 'Monterey');
insert into Streets (id, Name) values (24, 'Michigan');
insert into Streets (id, Name) values (25, 'Tony');
insert into Streets (id, Name) values (26, 'Maywood');
insert into Streets (id, Name) values (27, 'Scoville');
insert into Streets (id, Name) values (28, 'Forest');
insert into Streets (id, Name) values (29, 'Luster');
insert into Streets (id, Name) values (30, 'Claremont');
insert into Streets (id, Name) values (31, 'Arrowood');
insert into Streets (id, Name) values (32, 'Hagan');
insert into Streets (id, Name) values (33, 'Macpherson');
insert into Streets (id, Name) values (34, '6th');
insert into Streets (id, Name) values (35, 'Warbler');
insert into Streets (id, Name) values (36, 'Raven');
insert into Streets (id, Name) values (37, 'Hoard');
insert into Streets (id, Name) values (38, 'Westridge');
insert into Streets (id, Name) values (39, 'Vernon');
insert into Streets (id, Name) values (40, 'Montana');
insert into Streets (id, Name) values (41, 'Green Ridge');
insert into Streets (id, Name) values (42, 'Heffernan');
insert into Streets (id, Name) values (43, 'Porter');
insert into Streets (id, Name) values (44, 'Sullivan');
insert into Streets (id, Name) values (45, 'Paget');
insert into Streets (id, Name) values (46, 'Thompson');
insert into Streets (id, Name) values (47, 'Warner');
insert into Streets (id, Name) values (48, 'Reindahl');
insert into Streets (id, Name) values (49, 'Columbus');
insert into Streets (id, Name) values (50, 'Steensland');
insert into Streets (id, Name) values (51, 'Artisan');
insert into Streets (id, Name) values (52, 'Corry');
insert into Streets (id, Name) values (53, 'Jana');
insert into Streets (id, Name) values (54, 'South');
insert into Streets (id, Name) values (55, 'Kinsman');
insert into Streets (id, Name) values (56, 'Milwaukee');
insert into Streets (id, Name) values (57, 'Cordelia');
insert into Streets (id, Name) values (58, 'Mallory');
insert into Streets (id, Name) values (59, 'Tennessee');
insert into Streets (id, Name) values (60, 'Corscot');
insert into Streets (id, Name) values (61, 'Manley');
insert into Streets (id, Name) values (62, 'Kennedy');
insert into Streets (id, Name) values (63, 'Hanson');
insert into Streets (id, Name) values (64, 'Cascade');
insert into Streets (id, Name) values (65, 'Holmberg');
insert into Streets (id, Name) values (66, 'Caliangt');
insert into Streets (id, Name) values (67, 'Lyons');
insert into Streets (id, Name) values (68, 'Longview');
insert into Streets (id, Name) values (69, 'Warbler');
insert into Streets (id, Name) values (70, 'Glacier Hill');
insert into Streets (id, Name) values (71, 'Atwood');
insert into Streets (id, Name) values (72, 'Corscot');
insert into Streets (id, Name) values (73, 'Jackson');
insert into Streets (id, Name) values (74, 'Blackbird');
insert into Streets (id, Name) values (75, 'Randy');
insert into Streets (id, Name) values (76, 'Comanche');
insert into Streets (id, Name) values (77, 'Hagan');
insert into Streets (id, Name) values (78, 'Fairfield');
insert into Streets (id, Name) values (79, 'Rockefeller');
insert into Streets (id, Name) values (80, 'School');
insert into Streets (id, Name) values (81, 'Lotheville');
insert into Streets (id, Name) values (82, 'Oriole');
insert into Streets (id, Name) values (83, 'Lake View');
insert into Streets (id, Name) values (84, 'Canary');
insert into Streets (id, Name) values (85, 'Donald');
insert into Streets (id, Name) values (86, 'Oak');
insert into Streets (id, Name) values (87, 'Morning');
insert into Streets (id, Name) values (88, 'Union');
insert into Streets (id, Name) values (89, 'Harper');
insert into Streets (id, Name) values (90, 'Dakota');
insert into Streets (id, Name) values (91, 'Luster');
insert into Streets (id, Name) values (92, 'Butterfield');
insert into Streets (id, Name) values (93, 'Goodland');
insert into Streets (id, Name) values (94, 'Mosinee');
insert into Streets (id, Name) values (95, 'Mcguire');
insert into Streets (id, Name) values (96, 'Katie');
insert into Streets (id, Name) values (97, 'Park Meadow');
insert into Streets (id, Name) values (98, 'Meadow Ridge');
insert into Streets (id, Name) values (99, 'Ridgeway');
insert into Streets (id, Name) values (100, 'Messerschmidt');
insert into Streets (id, Name) values (101, 'Miller');
insert into Streets (id, Name) values (102, 'Village');
insert into Streets (id, Name) values (103, 'Schurz');
insert into Streets (id, Name) values (104, 'Stuart');
insert into Streets (id, Name) values (105, 'Donald');
insert into Streets (id, Name) values (106, 'Schurz');
insert into Streets (id, Name) values (107, 'Sunbrook');
insert into Streets (id, Name) values (108, 'Hintze');
insert into Streets (id, Name) values (109, 'Meadow Ridge');
insert into Streets (id, Name) values (110, 'Dahle');
insert into Streets (id, Name) values (111, 'Ludington');
insert into Streets (id, Name) values (112, 'Colorado');
insert into Streets (id, Name) values (113, 'Eastlawn');
insert into Streets (id, Name) values (114, 'Mesta');
insert into Streets (id, Name) values (115, 'Green');
insert into Streets (id, Name) values (116, 'Little Fleur');
insert into Streets (id, Name) values (117, 'Hovde');
insert into Streets (id, Name) values (118, 'Buell');
insert into Streets (id, Name) values (119, 'Vernon');
insert into Streets (id, Name) values (120, 'Spaight');
insert into Streets (id, Name) values (121, 'Huxley');
insert into Streets (id, Name) values (122, 'Park Meadow');
insert into Streets (id, Name) values (123, 'Merry');
insert into Streets (id, Name) values (124, 'Debs');
insert into Streets (id, Name) values (125, 'Harper');
insert into Streets (id, Name) values (126, 'Lawn');
insert into Streets (id, Name) values (127, 'Gulseth');
insert into Streets (id, Name) values (128, 'Delladonna');
insert into Streets (id, Name) values (129, 'Sloan');
insert into Streets (id, Name) values (130, 'Boyd');
insert into Streets (id, Name) values (131, 'Bellgrove');
insert into Streets (id, Name) values (132, 'Dryden');
insert into Streets (id, Name) values (133, 'Cascade');
insert into Streets (id, Name) values (134, 'Lighthouse Bay');
insert into Streets (id, Name) values (135, 'Farragut');
insert into Streets (id, Name) values (136, 'Oakridge');
insert into Streets (id, Name) values (137, 'Corscot');
insert into Streets (id, Name) values (138, 'Morningstar');
insert into Streets (id, Name) values (139, 'Dovetail');
insert into Streets (id, Name) values (140, 'Westridge');
insert into Streets (id, Name) values (141, 'Marquette');
insert into Streets (id, Name) values (142, 'Nancy');
insert into Streets (id, Name) values (143, 'Grayhawk');
insert into Streets (id, Name) values (144, 'Johnson');
insert into Streets (id, Name) values (145, 'Commercial');
insert into Streets (id, Name) values (146, 'Katie');
insert into Streets (id, Name) values (147, 'Meadow Valley');
insert into Streets (id, Name) values (148, 'Meadow Valley');
insert into Streets (id, Name) values (149, 'Ohio');
insert into Streets (id, Name) values (150, 'Norway Maple');
insert into Streets (id, Name) values (151, 'Shopko');
insert into Streets (id, Name) values (152, 'Prentice');
insert into Streets (id, Name) values (153, 'Dottie');
insert into Streets (id, Name) values (154, 'Emmet');
insert into Streets (id, Name) values (155, 'Mandrake');
insert into Streets (id, Name) values (156, 'Gateway');
insert into Streets (id, Name) values (157, 'South');
insert into Streets (id, Name) values (158, 'Jay');
insert into Streets (id, Name) values (159, 'Mccormick');
insert into Streets (id, Name) values (160, 'Bayside');
insert into Streets (id, Name) values (161, 'John Wall');
insert into Streets (id, Name) values (162, 'Daystar');
insert into Streets (id, Name) values (163, 'Magdeline');
insert into Streets (id, Name) values (164, 'Holmberg');
insert into Streets (id, Name) values (165, 'Dwight');
insert into Streets (id, Name) values (166, 'Dovetail');
insert into Streets (id, Name) values (167, 'Buhler');
insert into Streets (id, Name) values (168, 'Buell');
insert into Streets (id, Name) values (169, 'Loftsgordon');
insert into Streets (id, Name) values (170, 'Main');
insert into Streets (id, Name) values (171, 'Muir');
insert into Streets (id, Name) values (172, 'David');
insert into Streets (id, Name) values (173, 'Myrtle');
insert into Streets (id, Name) values (174, 'Laurel');
insert into Streets (id, Name) values (175, 'Hagan');
insert into Streets (id, Name) values (176, 'Scofield');
insert into Streets (id, Name) values (177, 'Milwaukee');
insert into Streets (id, Name) values (178, 'Coolidge');
insert into Streets (id, Name) values (179, 'Bunker Hill');
insert into Streets (id, Name) values (180, 'Service');
insert into Streets (id, Name) values (181, 'Spaight');
insert into Streets (id, Name) values (182, 'Stone Corner');
insert into Streets (id, Name) values (183, 'Dryden');
insert into Streets (id, Name) values (184, 'Valley Edge');
insert into Streets (id, Name) values (185, 'Stephen');
insert into Streets (id, Name) values (186, 'Shasta');
insert into Streets (id, Name) values (187, 'Hayes');
insert into Streets (id, Name) values (188, 'Truax');
insert into Streets (id, Name) values (189, 'Blue Bill Park');
insert into Streets (id, Name) values (190, 'Maryland');
insert into Streets (id, Name) values (191, 'Luster');
insert into Streets (id, Name) values (192, 'Sachs');
insert into Streets (id, Name) values (193, 'Sundown');
insert into Streets (id, Name) values (194, 'Elgar');
insert into Streets (id, Name) values (195, 'Carberry');
insert into Streets (id, Name) values (196, 'Nancy');
insert into Streets (id, Name) values (197, 'Morningstar');
insert into Streets (id, Name) values (198, 'Steensland');
insert into Streets (id, Name) values (199, 'Cambridge');
insert into Streets (id, Name) values (200, 'Raven');
insert into Streets (id, Name) values (201, 'Mallard');
insert into Streets (id, Name) values (202, 'Vernon');
insert into Streets (id, Name) values (203, 'Graedel');
insert into Streets (id, Name) values (204, 'Chive');
insert into Streets (id, Name) values (205, 'Vernon');
insert into Streets (id, Name) values (206, 'Rieder');
insert into Streets (id, Name) values (207, 'Redwing');
insert into Streets (id, Name) values (208, 'Warrior');
insert into Streets (id, Name) values (209, 'Westerfield');
insert into Streets (id, Name) values (210, 'Lerdahl');
insert into Streets (id, Name) values (211, 'Scofield');
insert into Streets (id, Name) values (212, 'Mosinee');
insert into Streets (id, Name) values (213, 'Gina');
insert into Streets (id, Name) values (214, 'Hagan');
insert into Streets (id, Name) values (215, 'Fuller');
insert into Streets (id, Name) values (216, 'Russell');
insert into Streets (id, Name) values (217, 'Porter');
insert into Streets (id, Name) values (218, 'Brentwood');
insert into Streets (id, Name) values (219, 'Rutledge');
insert into Streets (id, Name) values (220, 'Northwestern');
insert into Streets (id, Name) values (221, 'Manufacturers');
insert into Streets (id, Name) values (222, 'Village');
insert into Streets (id, Name) values (223, 'Ronald Regan');
insert into Streets (id, Name) values (224, 'Graedel');
insert into Streets (id, Name) values (225, 'Mosinee');
insert into Streets (id, Name) values (226, 'Gale');
insert into Streets (id, Name) values (227, 'Pennsylvania');
insert into Streets (id, Name) values (228, 'Doe Crossing');
insert into Streets (id, Name) values (229, 'Lake View');
insert into Streets (id, Name) values (230, '2nd');
insert into Streets (id, Name) values (231, 'Sutteridge');
insert into Streets (id, Name) values (232, 'Dennis');
insert into Streets (id, Name) values (233, 'Burrows');
insert into Streets (id, Name) values (234, 'Haas');
insert into Streets (id, Name) values (235, 'Ryan');
insert into Streets (id, Name) values (236, 'Old Shore');
insert into Streets (id, Name) values (237, 'Shoshone');
insert into Streets (id, Name) values (238, 'Delaware');
insert into Streets (id, Name) values (239, 'Service');
insert into Streets (id, Name) values (240, 'Fallview');
insert into Streets (id, Name) values (241, 'Myrtle');
insert into Streets (id, Name) values (242, 'Steensland');
insert into Streets (id, Name) values (243, 'Roth');
insert into Streets (id, Name) values (244, 'Weeping Birch');
insert into Streets (id, Name) values (245, 'Katie');
insert into Streets (id, Name) values (246, 'Logan');
insert into Streets (id, Name) values (247, 'Texas');
insert into Streets (id, Name) values (248, 'Mockingbird');
insert into Streets (id, Name) values (249, 'Roxbury');
insert into Streets (id, Name) values (250, 'Sutherland');
insert into Streets (id, Name) values (251, 'Buhler');
insert into Streets (id, Name) values (252, 'Colorado');
insert into Streets (id, Name) values (253, 'Loftsgordon');
insert into Streets (id, Name) values (254, 'Erie');
insert into Streets (id, Name) values (255, 'Charing Cross');
insert into Streets (id, Name) values (256, 'Daystar');
insert into Streets (id, Name) values (257, 'Monument');
insert into Streets (id, Name) values (258, 'Mayfield');
insert into Streets (id, Name) values (259, 'Manitowish');
insert into Streets (id, Name) values (260, 'Gale');
insert into Streets (id, Name) values (261, 'Towne');
insert into Streets (id, Name) values (262, 'Eastlawn');
insert into Streets (id, Name) values (263, 'Jay');
insert into Streets (id, Name) values (264, 'Dorton');
insert into Streets (id, Name) values (265, 'Oakridge');
insert into Streets (id, Name) values (266, 'East');
insert into Streets (id, Name) values (267, 'Stone Corner');
insert into Streets (id, Name) values (268, 'Fulton');
insert into Streets (id, Name) values (269, 'Old Gate');
insert into Streets (id, Name) values (270, 'Village Green');
insert into Streets (id, Name) values (271, 'Myrtle');
insert into Streets (id, Name) values (272, 'Erie');
insert into Streets (id, Name) values (273, 'Del Sol');
insert into Streets (id, Name) values (274, 'Summer Ridge');
insert into Streets (id, Name) values (275, 'Hanson');
insert into Streets (id, Name) values (276, 'Forest Run');
insert into Streets (id, Name) values (277, 'Haas');
insert into Streets (id, Name) values (278, 'Elka');
insert into Streets (id, Name) values (279, 'Village Green');
insert into Streets (id, Name) values (280, 'Red Cloud');
insert into Streets (id, Name) values (281, 'Eliot');
insert into Streets (id, Name) values (282, 'Stang');
insert into Streets (id, Name) values (283, 'Coolidge');
insert into Streets (id, Name) values (284, 'Nelson');
insert into Streets (id, Name) values (285, 'Superior');
insert into Streets (id, Name) values (286, 'Dovetail');
insert into Streets (id, Name) values (287, 'Bay');
insert into Streets (id, Name) values (288, 'La Follette');
insert into Streets (id, Name) values (289, 'Judy');
insert into Streets (id, Name) values (290, 'Transport');
insert into Streets (id, Name) values (291, 'Merrick');
insert into Streets (id, Name) values (292, 'Reinke');
insert into Streets (id, Name) values (293, 'Dennis');
insert into Streets (id, Name) values (294, 'Loeprich');
insert into Streets (id, Name) values (295, 'Shoshone');
insert into Streets (id, Name) values (296, 'Springs');
insert into Streets (id, Name) values (297, 'Colorado');
insert into Streets (id, Name) values (298, 'Armistice');
insert into Streets (id, Name) values (299, 'Menomonie');
insert into Streets (id, Name) values (300, 'Shoshone');
insert into Streets (id, Name) values (301, 'Red Cloud');
insert into Streets (id, Name) values (302, 'Memorial');
insert into Streets (id, Name) values (303, 'Kipling');
insert into Streets (id, Name) values (304, 'Leroy');
insert into Streets (id, Name) values (305, 'Randy');
insert into Streets (id, Name) values (306, 'Nova');
insert into Streets (id, Name) values (307, 'Ramsey');
insert into Streets (id, Name) values (308, 'Kropf');
insert into Streets (id, Name) values (309, 'Dwight');
insert into Streets (id, Name) values (310, 'Atwood');
insert into Streets (id, Name) values (311, 'Transport');
insert into Streets (id, Name) values (312, 'Harper');
insert into Streets (id, Name) values (313, 'Golf View');
insert into Streets (id, Name) values (314, 'Surrey');
insert into Streets (id, Name) values (315, 'Birchwood');
insert into Streets (id, Name) values (316, 'International');
insert into Streets (id, Name) values (317, 'Moose');
insert into Streets (id, Name) values (318, 'Anniversary');
insert into Streets (id, Name) values (319, 'Rutledge');
insert into Streets (id, Name) values (320, 'Myrtle');
insert into Streets (id, Name) values (321, 'Birchwood');
insert into Streets (id, Name) values (322, 'Shasta');
insert into Streets (id, Name) values (323, 'Waubesa');
insert into Streets (id, Name) values (324, 'Ridgeway');
insert into Streets (id, Name) values (325, 'Pawling');
insert into Streets (id, Name) values (326, 'Di Loreto');
insert into Streets (id, Name) values (327, 'Ramsey');
insert into Streets (id, Name) values (328, 'Colorado');
insert into Streets (id, Name) values (329, 'Petterle');
insert into Streets (id, Name) values (330, 'Mitchell');
insert into Streets (id, Name) values (331, 'Hayes');
insert into Streets (id, Name) values (332, 'Mifflin');
insert into Streets (id, Name) values (333, 'Graedel');
insert into Streets (id, Name) values (334, 'Talmadge');
insert into Streets (id, Name) values (335, 'Coolidge');
insert into Streets (id, Name) values (336, 'Anniversary');
insert into Streets (id, Name) values (337, 'Mallard');
insert into Streets (id, Name) values (338, 'Mallard');
insert into Streets (id, Name) values (339, 'Anderson');
insert into Streets (id, Name) values (340, 'Utah');
insert into Streets (id, Name) values (341, 'Hooker');
insert into Streets (id, Name) values (342, 'Dawn');
insert into Streets (id, Name) values (343, 'Russell');
insert into Streets (id, Name) values (344, 'Onsgard');
insert into Streets (id, Name) values (345, 'Rowland');
insert into Streets (id, Name) values (346, 'Karstens');
insert into Streets (id, Name) values (347, 'Holmberg');
insert into Streets (id, Name) values (348, 'Amoth');
insert into Streets (id, Name) values (349, 'Novick');
insert into Streets (id, Name) values (350, 'Columbus');
insert into Streets (id, Name) values (351, 'Melrose');
insert into Streets (id, Name) values (352, 'Atwood');
insert into Streets (id, Name) values (353, 'Corry');
insert into Streets (id, Name) values (354, 'Hayes');
insert into Streets (id, Name) values (355, 'Lunder');
insert into Streets (id, Name) values (356, 'Park Meadow');
insert into Streets (id, Name) values (357, 'Merchant');
insert into Streets (id, Name) values (358, 'Myrtle');
insert into Streets (id, Name) values (359, 'Ridge Oak');
insert into Streets (id, Name) values (360, 'Lillian');
insert into Streets (id, Name) values (361, 'Fulton');
insert into Streets (id, Name) values (362, 'Doe Crossing');
insert into Streets (id, Name) values (363, 'Crownhardt');
insert into Streets (id, Name) values (364, 'Loftsgordon');
insert into Streets (id, Name) values (365, 'Schlimgen');
insert into Streets (id, Name) values (366, 'Fallview');
insert into Streets (id, Name) values (367, 'Harper');
insert into Streets (id, Name) values (368, 'Coleman');
insert into Streets (id, Name) values (369, 'Hansons');
insert into Streets (id, Name) values (370, 'Talisman');
insert into Streets (id, Name) values (371, 'Oneill');
insert into Streets (id, Name) values (372, 'Morning');
insert into Streets (id, Name) values (373, 'Old Gate');
insert into Streets (id, Name) values (374, 'Redwing');
insert into Streets (id, Name) values (375, 'Grover');
insert into Streets (id, Name) values (376, 'Bartillon');
insert into Streets (id, Name) values (377, 'Rockefeller');
insert into Streets (id, Name) values (378, 'Daystar');
insert into Streets (id, Name) values (379, 'Ronald Regan');
insert into Streets (id, Name) values (380, 'Northfield');
insert into Streets (id, Name) values (381, 'Hansons');
insert into Streets (id, Name) values (382, 'Burning Wood');
insert into Streets (id, Name) values (383, 'Donald');
insert into Streets (id, Name) values (384, 'Armistice');
insert into Streets (id, Name) values (385, 'Acker');
insert into Streets (id, Name) values (386, 'Loeprich');
insert into Streets (id, Name) values (387, 'Prairie Rose');
insert into Streets (id, Name) values (388, 'Armistice');
insert into Streets (id, Name) values (389, 'Crowley');
insert into Streets (id, Name) values (390, 'Memorial');
insert into Streets (id, Name) values (391, 'Shasta');
insert into Streets (id, Name) values (392, 'Schiller');
insert into Streets (id, Name) values (393, 'Brown');
insert into Streets (id, Name) values (394, 'Ruskin');
insert into Streets (id, Name) values (395, 'Clyde Gallagher');
insert into Streets (id, Name) values (396, 'Vera');
insert into Streets (id, Name) values (397, 'Vidon');
insert into Streets (id, Name) values (398, 'Mayer');
insert into Streets (id, Name) values (399, 'Park Meadow');
insert into Streets (id, Name) values (400, '5th');
insert into Streets (id, Name) values (401, 'Glacier Hill');
insert into Streets (id, Name) values (402, 'Onsgard');
insert into Streets (id, Name) values (403, '3rd');
insert into Streets (id, Name) values (404, 'Magdeline');
insert into Streets (id, Name) values (405, 'Sunbrook');
insert into Streets (id, Name) values (406, 'Merrick');
insert into Streets (id, Name) values (407, 'Sachtjen');
insert into Streets (id, Name) values (408, 'Packers');
insert into Streets (id, Name) values (409, 'Eastlawn');
insert into Streets (id, Name) values (410, 'Ramsey');
insert into Streets (id, Name) values (411, 'Talisman');
insert into Streets (id, Name) values (412, 'Truax');
insert into Streets (id, Name) values (413, 'Thackeray');
insert into Streets (id, Name) values (414, 'Corscot');
insert into Streets (id, Name) values (415, 'Carberry');
insert into Streets (id, Name) values (416, 'Mitchell');
insert into Streets (id, Name) values (417, 'Mandrake');
insert into Streets (id, Name) values (418, 'Village');
insert into Streets (id, Name) values (419, 'Sundown');
insert into Streets (id, Name) values (420, 'Warbler');
insert into Streets (id, Name) values (421, 'Johnson');
insert into Streets (id, Name) values (422, 'Warner');
insert into Streets (id, Name) values (423, 'Melody');
insert into Streets (id, Name) values (424, 'Straubel');
insert into Streets (id, Name) values (425, 'Oneill');
insert into Streets (id, Name) values (426, 'Sutherland');
insert into Streets (id, Name) values (427, 'Garrison');
insert into Streets (id, Name) values (428, 'Nova');
insert into Streets (id, Name) values (429, 'Mesta');
insert into Streets (id, Name) values (430, 'Magdeline');
insert into Streets (id, Name) values (431, 'Holy Cross');
insert into Streets (id, Name) values (432, 'Carpenter');
insert into Streets (id, Name) values (433, 'Texas');
insert into Streets (id, Name) values (434, 'High Crossing');
insert into Streets (id, Name) values (435, 'Hayes');
insert into Streets (id, Name) values (436, 'Memorial');
insert into Streets (id, Name) values (437, 'Buena Vista');
insert into Streets (id, Name) values (438, 'Pennsylvania');
insert into Streets (id, Name) values (439, 'Welch');
insert into Streets (id, Name) values (440, 'Main');
insert into Streets (id, Name) values (441, 'Caliangt');
insert into Streets (id, Name) values (442, '6th');
insert into Streets (id, Name) values (443, 'Charing Cross');
insert into Streets (id, Name) values (444, 'Erie');
insert into Streets (id, Name) values (445, 'West');
insert into Streets (id, Name) values (446, 'Melrose');
insert into Streets (id, Name) values (447, 'Elka');
insert into Streets (id, Name) values (448, 'Harbort');
insert into Streets (id, Name) values (449, 'Merchant');
insert into Streets (id, Name) values (450, 'Fallview');
insert into Streets (id, Name) values (451, 'Di Loreto');
insert into Streets (id, Name) values (452, 'Carey');
insert into Streets (id, Name) values (453, 'Eagan');
insert into Streets (id, Name) values (454, 'Park Meadow');
insert into Streets (id, Name) values (455, 'Paget');
insert into Streets (id, Name) values (456, 'Kennedy');
insert into Streets (id, Name) values (457, 'Michigan');
insert into Streets (id, Name) values (458, 'Delaware');
insert into Streets (id, Name) values (459, 'Fremont');
insert into Streets (id, Name) values (460, 'Waywood');
insert into Streets (id, Name) values (461, 'Corry');
insert into Streets (id, Name) values (462, 'Bobwhite');
insert into Streets (id, Name) values (463, 'La Follette');
insert into Streets (id, Name) values (464, 'Nancy');
insert into Streets (id, Name) values (465, 'Westport');
insert into Streets (id, Name) values (466, '4th');
insert into Streets (id, Name) values (467, 'Merrick');
insert into Streets (id, Name) values (468, 'Morning');
insert into Streets (id, Name) values (469, 'Blackbird');
insert into Streets (id, Name) values (470, 'Dennis');
insert into Streets (id, Name) values (471, 'Clemons');
insert into Streets (id, Name) values (472, 'Havey');
insert into Streets (id, Name) values (473, 'Monterey');
insert into Streets (id, Name) values (474, 'Hintze');
insert into Streets (id, Name) values (475, 'Lighthouse Bay');
insert into Streets (id, Name) values (476, 'Drewry');
insert into Streets (id, Name) values (477, 'Amoth');
insert into Streets (id, Name) values (478, 'Northview');
insert into Streets (id, Name) values (479, 'Loftsgordon');
insert into Streets (id, Name) values (480, 'Boyd');
insert into Streets (id, Name) values (481, 'Cody');
insert into Streets (id, Name) values (482, 'Comanche');
insert into Streets (id, Name) values (483, 'Waywood');
insert into Streets (id, Name) values (484, 'Gerald');
insert into Streets (id, Name) values (485, 'Monterey');
insert into Streets (id, Name) values (486, 'Autumn Leaf');
insert into Streets (id, Name) values (487, 'Fieldstone');
insert into Streets (id, Name) values (488, 'Havey');
insert into Streets (id, Name) values (489, 'Surrey');
insert into Streets (id, Name) values (490, 'Leroy');
insert into Streets (id, Name) values (491, 'Nevada');
insert into Streets (id, Name) values (492, 'Alpine');
insert into Streets (id, Name) values (493, 'Monterey');
insert into Streets (id, Name) values (494, 'Marquette');
insert into Streets (id, Name) values (495, 'Lakeland');
insert into Streets (id, Name) values (496, 'Hintze');
insert into Streets (id, Name) values (497, 'Riverside');
insert into Streets (id, Name) values (498, 'Kinsman');
insert into Streets (id, Name) values (499, 'Independence');
insert into Streets (id, Name) values (500, 'Rockefeller');
insert into Streets (id, Name) values (501, 'Glendale');
insert into Streets (id, Name) values (502, 'Algoma');
insert into Streets (id, Name) values (503, 'Barnett');
insert into Streets (id, Name) values (504, 'Buena Vista');
insert into Streets (id, Name) values (505, 'Lakeland');
insert into Streets (id, Name) values (506, 'Johnson');
insert into Streets (id, Name) values (507, 'Heath');
insert into Streets (id, Name) values (508, 'Bunting');
insert into Streets (id, Name) values (509, 'Lukken');
insert into Streets (id, Name) values (510, 'Mallard');
insert into Streets (id, Name) values (511, 'Brown');
insert into Streets (id, Name) values (512, 'Troy');
insert into Streets (id, Name) values (513, 'Fordem');
insert into Streets (id, Name) values (514, 'Anthes');
insert into Streets (id, Name) values (515, 'Clarendon');
insert into Streets (id, Name) values (516, 'Bay');
insert into Streets (id, Name) values (517, 'International');
insert into Streets (id, Name) values (518, 'Washington');
insert into Streets (id, Name) values (519, 'Forest Dale');
insert into Streets (id, Name) values (520, 'Nova');
insert into Streets (id, Name) values (521, 'Cascade');
insert into Streets (id, Name) values (522, 'Briar Crest');
insert into Streets (id, Name) values (523, 'New Castle');
insert into Streets (id, Name) values (524, 'Rigney');
insert into Streets (id, Name) values (525, 'Garrison');
insert into Streets (id, Name) values (526, 'Moose');
insert into Streets (id, Name) values (527, 'Farragut');
insert into Streets (id, Name) values (528, 'Mandrake');
insert into Streets (id, Name) values (529, 'Briar Crest');
insert into Streets (id, Name) values (530, 'Sheridan');
insert into Streets (id, Name) values (531, 'Blue Bill Park');
insert into Streets (id, Name) values (532, 'Canary');
insert into Streets (id, Name) values (533, 'Chive');
insert into Streets (id, Name) values (534, 'Dovetail');
insert into Streets (id, Name) values (535, 'Coleman');
insert into Streets (id, Name) values (536, '4th');
insert into Streets (id, Name) values (537, 'Grim');
insert into Streets (id, Name) values (538, '3rd');
insert into Streets (id, Name) values (539, 'Florence');
insert into Streets (id, Name) values (540, 'Dovetail');
insert into Streets (id, Name) values (541, 'Summerview');
insert into Streets (id, Name) values (542, 'International');
insert into Streets (id, Name) values (543, 'Miller');
insert into Streets (id, Name) values (544, '8th');
insert into Streets (id, Name) values (545, 'Old Shore');
insert into Streets (id, Name) values (546, 'Bobwhite');
insert into Streets (id, Name) values (547, 'Vidon');
insert into Streets (id, Name) values (548, 'Corry');
insert into Streets (id, Name) values (549, 'Larry');
insert into Streets (id, Name) values (550, 'Northridge');
insert into Streets (id, Name) values (551, 'Shelley');
insert into Streets (id, Name) values (552, 'Forster');
insert into Streets (id, Name) values (553, 'Corscot');
insert into Streets (id, Name) values (554, 'Florence');
insert into Streets (id, Name) values (555, 'Eastwood');
insert into Streets (id, Name) values (556, 'Bultman');
insert into Streets (id, Name) values (557, 'Evergreen');
insert into Streets (id, Name) values (558, 'Memorial');
insert into Streets (id, Name) values (559, 'Brentwood');
insert into Streets (id, Name) values (560, 'Mayfield');
insert into Streets (id, Name) values (561, 'Claremont');
insert into Streets (id, Name) values (562, 'Bunting');
insert into Streets (id, Name) values (563, 'Del Sol');
insert into Streets (id, Name) values (564, 'Rutledge');
insert into Streets (id, Name) values (565, 'Marquette');
insert into Streets (id, Name) values (566, 'Sullivan');
insert into Streets (id, Name) values (567, 'Welch');
insert into Streets (id, Name) values (568, 'Toban');
insert into Streets (id, Name) values (569, 'Hanover');
insert into Streets (id, Name) values (570, 'Katie');
insert into Streets (id, Name) values (571, 'Atwood');
insert into Streets (id, Name) values (572, 'Nova');
insert into Streets (id, Name) values (573, 'Lindbergh');
insert into Streets (id, Name) values (574, 'Mallard');
insert into Streets (id, Name) values (575, 'Northwestern');
insert into Streets (id, Name) values (576, 'Golf');
insert into Streets (id, Name) values (577, 'Sheridan');
insert into Streets (id, Name) values (578, 'Aberg');
insert into Streets (id, Name) values (579, 'Anderson');
insert into Streets (id, Name) values (580, 'Lillian');
insert into Streets (id, Name) values (581, 'Schmedeman');
insert into Streets (id, Name) values (582, 'Corry');
insert into Streets (id, Name) values (583, 'Cody');
insert into Streets (id, Name) values (584, 'Katie');
insert into Streets (id, Name) values (585, 'Welch');
insert into Streets (id, Name) values (586, 'Gina');
insert into Streets (id, Name) values (587, 'Cambridge');
insert into Streets (id, Name) values (588, 'Clyde Gallagher');
insert into Streets (id, Name) values (589, 'Carey');
insert into Streets (id, Name) values (590, 'Debra');
insert into Streets (id, Name) values (591, 'Golf Course');
insert into Streets (id, Name) values (592, 'Moulton');
insert into Streets (id, Name) values (593, 'Roxbury');
insert into Streets (id, Name) values (594, 'Eagle Crest');
insert into Streets (id, Name) values (595, 'Porter');
insert into Streets (id, Name) values (596, 'Straubel');
insert into Streets (id, Name) values (597, '2nd');
insert into Streets (id, Name) values (598, 'Hollow Ridge');
insert into Streets (id, Name) values (599, 'Golf View');
insert into Streets (id, Name) values (600, 'Anthes');
insert into Streets (id, Name) values (601, 'Oak');
insert into Streets (id, Name) values (602, 'Dovetail');
insert into Streets (id, Name) values (603, 'Jenifer');
insert into Streets (id, Name) values (604, 'Wayridge');
insert into Streets (id, Name) values (605, '6th');
insert into Streets (id, Name) values (606, 'Homewood');
insert into Streets (id, Name) values (607, 'Milwaukee');
insert into Streets (id, Name) values (608, 'Mockingbird');
insert into Streets (id, Name) values (609, 'Ridge Oak');
insert into Streets (id, Name) values (610, '1st');
insert into Streets (id, Name) values (611, 'Independence');
insert into Streets (id, Name) values (612, 'Fallview');
insert into Streets (id, Name) values (613, 'Clyde Gallagher');
insert into Streets (id, Name) values (614, 'Portage');
insert into Streets (id, Name) values (615, 'Transport');
insert into Streets (id, Name) values (616, 'Helena');
insert into Streets (id, Name) values (617, 'Cherokee');
insert into Streets (id, Name) values (618, 'Oak Valley');
insert into Streets (id, Name) values (619, 'Iowa');
insert into Streets (id, Name) values (620, 'Heath');
insert into Streets (id, Name) values (621, 'Myrtle');
insert into Streets (id, Name) values (622, 'Kingsford');
insert into Streets (id, Name) values (623, 'Jackson');
insert into Streets (id, Name) values (624, 'Dunning');
insert into Streets (id, Name) values (625, 'Summer Ridge');
insert into Streets (id, Name) values (626, 'Eastlawn');
insert into Streets (id, Name) values (627, 'Arizona');
insert into Streets (id, Name) values (628, 'Tony');
insert into Streets (id, Name) values (629, 'Toban');
insert into Streets (id, Name) values (630, 'Canary');
insert into Streets (id, Name) values (631, 'Sutherland');
insert into Streets (id, Name) values (632, 'Susan');
insert into Streets (id, Name) values (633, 'Muir');
insert into Streets (id, Name) values (634, 'Hoffman');
insert into Streets (id, Name) values (635, 'Maywood');
insert into Streets (id, Name) values (636, 'Upham');
insert into Streets (id, Name) values (637, '1st');
insert into Streets (id, Name) values (638, 'Anzinger');
insert into Streets (id, Name) values (639, 'Loeprich');
insert into Streets (id, Name) values (640, 'South');
insert into Streets (id, Name) values (641, 'Vahlen');
insert into Streets (id, Name) values (642, 'Pine View');
insert into Streets (id, Name) values (643, 'Laurel');
insert into Streets (id, Name) values (644, 'Golden Leaf');
insert into Streets (id, Name) values (645, 'Loeprich');
insert into Streets (id, Name) values (646, 'Corry');
insert into Streets (id, Name) values (647, 'Browning');
insert into Streets (id, Name) values (648, 'Redwing');
insert into Streets (id, Name) values (649, 'Westport');
insert into Streets (id, Name) values (650, 'Talmadge');
insert into Streets (id, Name) values (651, 'Mallard');
insert into Streets (id, Name) values (652, 'Farmco');
insert into Streets (id, Name) values (653, 'Summit');
insert into Streets (id, Name) values (654, 'Morrow');
insert into Streets (id, Name) values (655, 'Logan');
insert into Streets (id, Name) values (656, 'Arizona');
insert into Streets (id, Name) values (657, 'Longview');
insert into Streets (id, Name) values (658, 'Columbus');
insert into Streets (id, Name) values (659, 'Onsgard');
insert into Streets (id, Name) values (660, 'Loeprich');
insert into Streets (id, Name) values (661, 'Calypso');
insert into Streets (id, Name) values (662, 'Sutherland');
insert into Streets (id, Name) values (663, 'Fordem');
insert into Streets (id, Name) values (664, 'Duke');
insert into Streets (id, Name) values (665, 'Anhalt');
insert into Streets (id, Name) values (666, 'Mesta');
insert into Streets (id, Name) values (667, 'Reindahl');
insert into Streets (id, Name) values (668, 'Kedzie');
insert into Streets (id, Name) values (669, 'Lakeland');
insert into Streets (id, Name) values (670, 'Bay');
insert into Streets (id, Name) values (671, 'Dunning');
insert into Streets (id, Name) values (672, '6th');
insert into Streets (id, Name) values (673, 'Grim');
insert into Streets (id, Name) values (674, 'Thompson');
insert into Streets (id, Name) values (675, 'Cherokee');
insert into Streets (id, Name) values (676, 'Mosinee');
insert into Streets (id, Name) values (677, 'High Crossing');
insert into Streets (id, Name) values (678, 'Moland');
insert into Streets (id, Name) values (679, 'Arizona');
insert into Streets (id, Name) values (680, 'Trailsway');
insert into Streets (id, Name) values (681, 'Parkside');
insert into Streets (id, Name) values (682, 'Tony');
insert into Streets (id, Name) values (683, 'Texas');
insert into Streets (id, Name) values (684, 'Cascade');
insert into Streets (id, Name) values (685, 'Twin Pines');
insert into Streets (id, Name) values (686, 'Steensland');
insert into Streets (id, Name) values (687, 'Manley');
insert into Streets (id, Name) values (688, 'Fairfield');
insert into Streets (id, Name) values (689, 'Dakota');
insert into Streets (id, Name) values (690, 'Holmberg');
insert into Streets (id, Name) values (691, 'Stephen');
insert into Streets (id, Name) values (692, 'Starling');
insert into Streets (id, Name) values (693, 'Gale');
insert into Streets (id, Name) values (694, 'Lyons');
insert into Streets (id, Name) values (695, 'Independence');
insert into Streets (id, Name) values (696, 'Merrick');
insert into Streets (id, Name) values (697, 'Eastlawn');
insert into Streets (id, Name) values (698, 'Spohn');
insert into Streets (id, Name) values (699, 'Pankratz');
insert into Streets (id, Name) values (700, 'Morningstar');
insert into Streets (id, Name) values (701, 'Blue Bill Park');
insert into Streets (id, Name) values (702, 'Sundown');
insert into Streets (id, Name) values (703, 'Donald');
insert into Streets (id, Name) values (704, 'Brown');
insert into Streets (id, Name) values (705, 'Portage');
insert into Streets (id, Name) values (706, 'Ryan');
insert into Streets (id, Name) values (707, 'Rutledge');
insert into Streets (id, Name) values (708, 'Badeau');
insert into Streets (id, Name) values (709, 'La Follette');
insert into Streets (id, Name) values (710, 'Schurz');
insert into Streets (id, Name) values (711, '3rd');
insert into Streets (id, Name) values (712, 'Esch');
insert into Streets (id, Name) values (713, 'Rieder');
insert into Streets (id, Name) values (714, 'Pierstorff');
insert into Streets (id, Name) values (715, 'Bartillon');
insert into Streets (id, Name) values (716, 'Westport');
insert into Streets (id, Name) values (717, 'John Wall');
insert into Streets (id, Name) values (718, 'Maryland');
insert into Streets (id, Name) values (719, 'Northwestern');
insert into Streets (id, Name) values (720, 'Marcy');
insert into Streets (id, Name) values (721, 'Mcguire');
insert into Streets (id, Name) values (722, 'Arkansas');
insert into Streets (id, Name) values (723, 'Memorial');
insert into Streets (id, Name) values (724, 'Anhalt');
insert into Streets (id, Name) values (725, 'Vermont');
insert into Streets (id, Name) values (726, 'Orin');
insert into Streets (id, Name) values (727, 'Harper');
insert into Streets (id, Name) values (728, 'Banding');
insert into Streets (id, Name) values (729, 'Mitchell');
insert into Streets (id, Name) values (730, 'Thompson');
insert into Streets (id, Name) values (731, 'Graedel');
insert into Streets (id, Name) values (732, 'Doe Crossing');
insert into Streets (id, Name) values (733, 'Northridge');
insert into Streets (id, Name) values (734, 'Garrison');
insert into Streets (id, Name) values (735, 'Old Shore');
insert into Streets (id, Name) values (736, 'Kensington');
insert into Streets (id, Name) values (737, 'Dovetail');
insert into Streets (id, Name) values (738, 'Maywood');
insert into Streets (id, Name) values (739, 'Caliangt');
insert into Streets (id, Name) values (740, 'Warner');
insert into Streets (id, Name) values (741, 'Sommers');
insert into Streets (id, Name) values (742, 'Loftsgordon');
insert into Streets (id, Name) values (743, 'Goodland');
insert into Streets (id, Name) values (744, 'Banding');
insert into Streets (id, Name) values (745, 'Thompson');
insert into Streets (id, Name) values (746, 'Schlimgen');
insert into Streets (id, Name) values (747, 'Sloan');
insert into Streets (id, Name) values (748, 'Sullivan');
insert into Streets (id, Name) values (749, 'Everett');
insert into Streets (id, Name) values (750, 'Stang');
insert into Streets (id, Name) values (751, 'Cottonwood');
insert into Streets (id, Name) values (752, 'Straubel');
insert into Streets (id, Name) values (753, 'Harper');
insert into Streets (id, Name) values (754, 'Novick');
insert into Streets (id, Name) values (755, 'Welch');
insert into Streets (id, Name) values (756, 'Eagan');
insert into Streets (id, Name) values (757, 'Daystar');
insert into Streets (id, Name) values (758, 'Messerschmidt');
insert into Streets (id, Name) values (759, 'Southridge');
insert into Streets (id, Name) values (760, 'Caliangt');
insert into Streets (id, Name) values (761, 'Sheridan');
insert into Streets (id, Name) values (762, 'Moland');
insert into Streets (id, Name) values (763, 'Division');
insert into Streets (id, Name) values (764, 'East');
insert into Streets (id, Name) values (765, 'Barnett');
insert into Streets (id, Name) values (766, 'Grim');
insert into Streets (id, Name) values (767, 'Kensington');
insert into Streets (id, Name) values (768, 'Vermont');
insert into Streets (id, Name) values (769, 'Superior');
insert into Streets (id, Name) values (770, 'Division');
insert into Streets (id, Name) values (771, 'Eagan');
insert into Streets (id, Name) values (772, 'Tomscot');
insert into Streets (id, Name) values (773, 'Truax');
insert into Streets (id, Name) values (774, 'Union');
insert into Streets (id, Name) values (775, 'Pond');
insert into Streets (id, Name) values (776, 'Canary');
insert into Streets (id, Name) values (777, 'Carey');
insert into Streets (id, Name) values (778, 'Bowman');
insert into Streets (id, Name) values (779, 'Forest Run');
insert into Streets (id, Name) values (780, 'Hansons');
insert into Streets (id, Name) values (781, 'Green Ridge');
insert into Streets (id, Name) values (782, 'Hagan');
insert into Streets (id, Name) values (783, 'Lerdahl');
insert into Streets (id, Name) values (784, 'Jenifer');
insert into Streets (id, Name) values (785, 'Memorial');
insert into Streets (id, Name) values (786, 'Blackbird');
insert into Streets (id, Name) values (787, 'Summer Ridge');
insert into Streets (id, Name) values (788, 'Reinke');
insert into Streets (id, Name) values (789, 'Warbler');
insert into Streets (id, Name) values (790, 'Hayes');
insert into Streets (id, Name) values (791, 'Oxford');
insert into Streets (id, Name) values (792, 'Sunnyside');
insert into Streets (id, Name) values (793, 'Roth');
insert into Streets (id, Name) values (794, 'Meadow Vale');
insert into Streets (id, Name) values (795, 'Claremont');
insert into Streets (id, Name) values (796, 'Marquette');
insert into Streets (id, Name) values (797, 'Evergreen');
insert into Streets (id, Name) values (798, 'Vera');
insert into Streets (id, Name) values (799, 'Hallows');
insert into Streets (id, Name) values (800, 'Tennessee');
insert into Streets (id, Name) values (801, 'Pond');
insert into Streets (id, Name) values (802, 'Meadow Ridge');
insert into Streets (id, Name) values (803, 'Mariners Cove');
insert into Streets (id, Name) values (804, 'Melby');
insert into Streets (id, Name) values (805, 'Lakewood Gardens');
insert into Streets (id, Name) values (806, 'Morning');
insert into Streets (id, Name) values (807, 'Washington');
insert into Streets (id, Name) values (808, 'Division');
insert into Streets (id, Name) values (809, 'Monica');
insert into Streets (id, Name) values (810, 'Muir');
insert into Streets (id, Name) values (811, 'Hansons');
insert into Streets (id, Name) values (812, 'Lillian');
insert into Streets (id, Name) values (813, 'Sheridan');
insert into Streets (id, Name) values (814, 'Anderson');
insert into Streets (id, Name) values (815, 'Ryan');
insert into Streets (id, Name) values (816, 'Mockingbird');
insert into Streets (id, Name) values (817, 'Melby');
insert into Streets (id, Name) values (818, 'Laurel');
insert into Streets (id, Name) values (819, 'Nelson');
insert into Streets (id, Name) values (820, 'Toban');
insert into Streets (id, Name) values (821, 'Jackson');
insert into Streets (id, Name) values (822, 'Mesta');
insert into Streets (id, Name) values (823, 'Pennsylvania');
insert into Streets (id, Name) values (824, 'Delladonna');
insert into Streets (id, Name) values (825, 'Sage');
insert into Streets (id, Name) values (826, 'Messerschmidt');
insert into Streets (id, Name) values (827, 'Brown');
insert into Streets (id, Name) values (828, 'Hagan');
insert into Streets (id, Name) values (829, 'Quincy');
insert into Streets (id, Name) values (830, 'Dapin');
insert into Streets (id, Name) values (831, 'Scofield');
insert into Streets (id, Name) values (832, 'Holmberg');
insert into Streets (id, Name) values (833, 'Erie');
insert into Streets (id, Name) values (834, 'Eliot');
insert into Streets (id, Name) values (835, 'Browning');
insert into Streets (id, Name) values (836, 'Talmadge');
insert into Streets (id, Name) values (837, 'Monument');
insert into Streets (id, Name) values (838, 'Dennis');
insert into Streets (id, Name) values (839, 'Acker');
insert into Streets (id, Name) values (840, 'Stang');
insert into Streets (id, Name) values (841, 'Northridge');
insert into Streets (id, Name) values (842, 'Montana');
insert into Streets (id, Name) values (843, 'Northwestern');
insert into Streets (id, Name) values (844, 'Bluestem');
insert into Streets (id, Name) values (845, '2nd');
insert into Streets (id, Name) values (846, 'Lakeland');
insert into Streets (id, Name) values (847, 'Menomonie');
insert into Streets (id, Name) values (848, 'Raven');
insert into Streets (id, Name) values (849, 'Vahlen');
insert into Streets (id, Name) values (850, 'Coolidge');
insert into Streets (id, Name) values (851, 'Surrey');
insert into Streets (id, Name) values (852, '4th');
insert into Streets (id, Name) values (853, 'Colorado');
insert into Streets (id, Name) values (854, 'Shelley');
insert into Streets (id, Name) values (855, 'Continental');
insert into Streets (id, Name) values (856, 'Brown');
insert into Streets (id, Name) values (857, 'Vidon');
insert into Streets (id, Name) values (858, 'Goodland');
insert into Streets (id, Name) values (859, 'Spenser');
insert into Streets (id, Name) values (860, 'Pine View');
insert into Streets (id, Name) values (861, 'Ridge Oak');
insert into Streets (id, Name) values (862, 'Orin');
insert into Streets (id, Name) values (863, 'American');
insert into Streets (id, Name) values (864, 'Carioca');
insert into Streets (id, Name) values (865, 'Arkansas');
insert into Streets (id, Name) values (866, 'John Wall');
insert into Streets (id, Name) values (867, 'Loeprich');
insert into Streets (id, Name) values (868, 'Main');
insert into Streets (id, Name) values (869, 'Iowa');
insert into Streets (id, Name) values (870, 'Thackeray');
insert into Streets (id, Name) values (871, 'Lerdahl');
insert into Streets (id, Name) values (872, 'Merrick');
insert into Streets (id, Name) values (873, 'Raven');
insert into Streets (id, Name) values (874, 'Sycamore');
insert into Streets (id, Name) values (875, 'Cascade');
insert into Streets (id, Name) values (876, 'Rigney');
insert into Streets (id, Name) values (877, 'Redwing');
insert into Streets (id, Name) values (878, 'Riverside');
insert into Streets (id, Name) values (879, 'Blue Bill Park');
insert into Streets (id, Name) values (880, 'Dunning');
insert into Streets (id, Name) values (881, 'Riverside');
insert into Streets (id, Name) values (882, 'Nancy');
insert into Streets (id, Name) values (883, 'Pawling');
insert into Streets (id, Name) values (884, 'Chinook');
insert into Streets (id, Name) values (885, 'Warbler');
insert into Streets (id, Name) values (886, 'Delaware');
insert into Streets (id, Name) values (887, 'Straubel');
insert into Streets (id, Name) values (888, 'Hoard');
insert into Streets (id, Name) values (889, 'Forest Run');
insert into Streets (id, Name) values (890, 'Forster');
insert into Streets (id, Name) values (891, '7th');
insert into Streets (id, Name) values (892, 'Hoepker');
insert into Streets (id, Name) values (893, 'Express');
insert into Streets (id, Name) values (894, 'Carpenter');
insert into Streets (id, Name) values (895, 'Hintze');
insert into Streets (id, Name) values (896, 'Columbus');
insert into Streets (id, Name) values (897, 'Green Ridge');
insert into Streets (id, Name) values (898, 'Mockingbird');
insert into Streets (id, Name) values (899, 'Clove');
insert into Streets (id, Name) values (900, 'Jackson');
insert into Streets (id, Name) values (901, 'Manley');
insert into Streets (id, Name) values (902, 'Buena Vista');
insert into Streets (id, Name) values (903, 'Anzinger');
insert into Streets (id, Name) values (904, 'Corry');
insert into Streets (id, Name) values (905, 'Bellgrove');
insert into Streets (id, Name) values (906, 'Maryland');
insert into Streets (id, Name) values (907, 'Bowman');
insert into Streets (id, Name) values (908, 'Troy');
insert into Streets (id, Name) values (909, 'Montana');
insert into Streets (id, Name) values (910, 'Graceland');
insert into Streets (id, Name) values (911, 'Green');
insert into Streets (id, Name) values (912, 'Fuller');
insert into Streets (id, Name) values (913, 'Ridge Oak');
insert into Streets (id, Name) values (914, 'Hanover');
insert into Streets (id, Name) values (915, 'Garrison');
insert into Streets (id, Name) values (916, 'Shoshone');
insert into Streets (id, Name) values (917, 'Di Loreto');
insert into Streets (id, Name) values (918, 'Gulseth');
insert into Streets (id, Name) values (919, 'Glendale');
insert into Streets (id, Name) values (920, 'Havey');
insert into Streets (id, Name) values (921, 'Village Green');
insert into Streets (id, Name) values (922, 'Namekagon');
insert into Streets (id, Name) values (923, 'Mockingbird');
insert into Streets (id, Name) values (924, 'Nevada');
insert into Streets (id, Name) values (925, 'Saint Paul');
insert into Streets (id, Name) values (926, 'Northfield');
insert into Streets (id, Name) values (927, 'Hansons');
insert into Streets (id, Name) values (928, 'Melvin');
insert into Streets (id, Name) values (929, 'Sauthoff');
insert into Streets (id, Name) values (930, 'Daystar');
insert into Streets (id, Name) values (931, 'Talmadge');
insert into Streets (id, Name) values (932, 'Erie');
insert into Streets (id, Name) values (933, 'Roth');
insert into Streets (id, Name) values (934, 'Annamark');
insert into Streets (id, Name) values (935, 'Rockefeller');
insert into Streets (id, Name) values (936, 'Anniversary');
insert into Streets (id, Name) values (937, 'Hazelcrest');
insert into Streets (id, Name) values (938, 'Clyde Gallagher');
insert into Streets (id, Name) values (939, 'Maryland');
insert into Streets (id, Name) values (940, 'Loftsgordon');
insert into Streets (id, Name) values (941, 'Crest Line');
insert into Streets (id, Name) values (942, 'Golf');
insert into Streets (id, Name) values (943, 'Southridge');
insert into Streets (id, Name) values (944, 'Larry');
insert into Streets (id, Name) values (945, 'Cascade');
insert into Streets (id, Name) values (946, 'Vahlen');
insert into Streets (id, Name) values (947, 'Mallory');
insert into Streets (id, Name) values (948, 'Dryden');
insert into Streets (id, Name) values (949, 'Lunder');
insert into Streets (id, Name) values (950, 'Eastlawn');
insert into Streets (id, Name) values (951, 'Upham');
insert into Streets (id, Name) values (952, 'Old Shore');
insert into Streets (id, Name) values (953, 'Blaine');
insert into Streets (id, Name) values (954, 'Porter');
insert into Streets (id, Name) values (955, 'Little Fleur');
insert into Streets (id, Name) values (956, 'Bunting');
insert into Streets (id, Name) values (957, 'Gale');
insert into Streets (id, Name) values (958, 'Cottonwood');
insert into Streets (id, Name) values (959, 'Declaration');
insert into Streets (id, Name) values (960, 'Darwin');
insert into Streets (id, Name) values (961, 'Oxford');
insert into Streets (id, Name) values (962, 'Parkside');
insert into Streets (id, Name) values (963, 'Monica');
insert into Streets (id, Name) values (964, '3rd');
insert into Streets (id, Name) values (965, 'John Wall');
insert into Streets (id, Name) values (966, 'Dwight');
insert into Streets (id, Name) values (967, 'Lakeland');
insert into Streets (id, Name) values (968, 'Express');
insert into Streets (id, Name) values (969, 'Holmberg');
insert into Streets (id, Name) values (970, 'Northland');
insert into Streets (id, Name) values (971, 'Golden Leaf');
insert into Streets (id, Name) values (972, 'Sycamore');
insert into Streets (id, Name) values (973, '2nd');
insert into Streets (id, Name) values (974, 'Armistice');
insert into Streets (id, Name) values (975, 'Colorado');
insert into Streets (id, Name) values (976, 'Russell');
insert into Streets (id, Name) values (977, 'Drewry');
insert into Streets (id, Name) values (978, 'Tennessee');
insert into Streets (id, Name) values (979, 'Mifflin');
insert into Streets (id, Name) values (980, 'Jenna');
insert into Streets (id, Name) values (981, 'Crest Line');
insert into Streets (id, Name) values (982, 'Pond');
insert into Streets (id, Name) values (983, 'Jenifer');
insert into Streets (id, Name) values (984, 'Bartillon');
insert into Streets (id, Name) values (985, 'Mcbride');
insert into Streets (id, Name) values (986, 'Center');
insert into Streets (id, Name) values (987, 'Nancy');
insert into Streets (id, Name) values (988, 'Hollow Ridge');
insert into Streets (id, Name) values (989, 'Schurz');
insert into Streets (id, Name) values (990, 'Scott');
insert into Streets (id, Name) values (991, 'Tennyson');
insert into Streets (id, Name) values (992, 'Ryan');
insert into Streets (id, Name) values (993, 'Morningstar');
insert into Streets (id, Name) values (994, 'Johnson');
insert into Streets (id, Name) values (995, 'Lukken');
insert into Streets (id, Name) values (996, 'Little Fleur');
insert into Streets (id, Name) values (997, 'Loftsgordon');
insert into Streets (id, Name) values (998, 'Larry');
insert into Streets (id, Name) values (999, 'Oneill');
insert into Streets (id, Name) values (1000, 'Derek');
